### ISSUE TITLE
make reverse easier to use

### ISSUE THREAD

**Issue by dominictarr** [Level/levelup#110]
right now, if you want to read a range in reverse mode,
it's tricky, because you have to reverse the order of the start and end too.

Forward:
``` js
db.createReadStream({start: 'A', end: 'Z'})
```
Reverse:
``` js
db.createReadStream({start: 'Z', end: 'A', reverse: true})
```

this is redundant, this feature would be much easier to use if you could do

``` js
db.createReadStream({start: 'A', end: 'Z', reverse: true})
```

And levelup would just see that start < end, and you are in reverse mode, and switch them around.

Alternatively, you could emit an error if the range was wrong, but I think I prefer just switching the order.

**Comment by ralphtheninja** [comment]
I believe this was resolved by introducing `lte` and `gte`. Please reopen if needed.
