### ISSUE TITLE
website

### ISSUE THREAD

**Issue by juliangruber** [Level/levelup#125]
As in #122.

It would be cool to have a website. Ones that I really like for open source projects are:

* http://voxeljs.com/
* http://www.tus.io/

What they have is:

* an introduction
* runnable examples
* tutorials to get started

we could use a indexdb wrapper thing to do this

* an architectural overview
* featured modules & tools

We have awesome modules and tools already

* a live stream of community activity

Kinda nice.

* a newsletter

Kinda nice.

* pictures of everyone involved

Super nice.

* a blog

Maybe?

What do you guys think?

**Comment by ralphtheninja** [comment]
http://leveldb.org/

Yes it is :)
