### ISSUE TITLE
Make default batch `'type'` = `'put'`

### ISSUE THREAD

**Issue by rvagg** [Level/levelup#141]
Shal we just make it so that:

```js
db.batch([{ key: 'foo', value: 'bar' }])
```

does this:

```js
db.batch([{ type: 'put', key: 'foo', value: 'bar' }])
```

i.e. if you leave out the `'type'` and have both a `'key'` and `'value'` then assume it's a `type='put'`?

**Comment by ralphtheninja** [comment]
Yes. Working on it.
