### ISSUE TITLE
Document lt/lte/gt/gte

### ISSUE THREAD

**Issue by rvagg** [Level/levelup#201]
LevelDOWN has had this for a little while now but it's not documented. We should remove reference to `'start'` and `'end'` (perhaps just note that they *used* to be the way to do it and they are kept for backward-compat).

Docs need both here and in LevelDOWN.

**Comment by TimothyGu** [comment]
This should be closed as #258 was merged.

**Comment by ralphtheninja** [comment]
@TimothyGu Correct. Thanks!
