### ISSUE TITLE
Expose a batch get method

### ISSUE THREAD

**Issue by JerrySievert** [Level/levelup#209]
We have some requirements to retrieve large numbers of records as quickly as possible.

It would be nice to have the ability to either:

```
   db.get([...]);
```

or

```
  db.batch()
  .get('father')
  .get('name')
```

Streaming and filtering is not necessarily an option, as we are retrieving ~1500 records per request, out of 1.24million.

Making a batch request and streaming the results would be optimal.

Thoughts?

/cc @dominictarr

**Comment by juliangruber** [comment]
we can add this to levelup as soon as enough backends support it, but for now this is not an option
