### ISSUE TITLE
error  :LOCK: already held by process  ?

### ISSUE THREAD

**Issue by robinxc** [Level/levelup#211]
MY CODE:

var     local_cfg = './db_cfg'
    ,option_cfg = { createIfMissing: true,
                    errorIfExists: false,
                    max_open_files:200,
                    write_buffer_size:100000000,
                    batch:1024,
                    valueEncoding: 'json' }

db_cfg = level(local_cfg,option_cfg)

.........................

db_cfg.close()

...........
db_cfg = level(local_cfg,option_cfg)

....
db_cfg.close()

---

error   log:

events.js:72
        throw er; // Unhandled 'error' event
              ^
OpenError: IO error: lock ./db_cfg/LOCK: already held by process
    at /home/Router/node_modules/level/node_modules/level-packager/node_modules/levelup/lib/levelup.js:105:34

**Comment by tnguyen14** [comment]
In my application, when should I call `db.close()`? If I am publishing a new version of the app to replace the old one, I am running into this issue as the lock was not released.

**Comment by avril-verhaeghen** [comment]
Having this issue now too. But I can't find information on how to unlock the LOCK file. Any ideas? Thanks

**Comment by juliangruber** [comment]
Maybe on this event would work: https://nodejs.org/api/process.html#process_event_beforeexit
