### ISSUE TITLE
wanted: cloud stress tester

### ISSUE THREAD

**Issue by juliangruber** [Level/levelup#217]
We have benchmarks and we have tests, but we don't have stress tests.

I have a server that's idling at ~5% most of the time and I'm sure there are many others that have one too, and would like to give it more purpose.

I imagine a set of predefined programs that will run one after another, either until they crash or a predefined "good enough" timeout - like one week - is reached.

So the stress tests don't slow down the whole server, they should be smart about cpu usage and throttle themself when necessary.

To ensure they don't consume too much disk space, they should clean up after x iterations.

Ideally each backend should get a fair chance of being picked for stress tests and before there's a new release pending or a particular bug it should be preferred over others.

What do you guys think?

**Comment by vweevers** [comment]
I don't think this is necessary anymore (would be nice to have, but it's not essential):

- We have tons of unit tests that are triggered in CI, not only by PRs but also by Greenkeeper in the background (when any dependency releases a new version, whether in-range or not). Plus some projects have multiple Travis and AppVeyor jobs.
- In `leveldown` we recently added extra iterations on (GC) tests that would only fail randomly
- Many people are running `level*` in production!
