### ISSUE TITLE
Expose levelup Errors on db.

### ISSUE THREAD

**Issue by timoxley** [Level/levelup#218]
It'd be handy for people implementing wrappers and plugins to be able to easily produce levelup-compatible errors.

AFAIK, anything that doesn't require levelup directly has no access to the "native"  levelup error objects. 

Perhaps `require('levelup/errors')` is just fine, though many libs don't depend on levelup directly, instead they expect a levelup db instance to be injected. This means if they don't use `"peerDependencies": {"levelup": "*"}`, it's possible errors they generate from their levelup may not match the signature of the errors in their db instance.

Some possible APIs:

```js
// createError method
throw db.createError('NotFoundError', key)
// expose via a map at db.errors
throw new db.errors.NotFoundError(key)
// expose on db directly
throw new db.NotFoundError(key)
```

I'll knock up a PR for this if you think it's a good idea.

**Comment by slang800** [comment]
It would be nice if `require('levelup/errors')` worked... kinda was surprised that I couldn't require it directly.

**Comment by jcrugzz** [comment]
@slang800 use`levelup/lib/errors` for now but yea this would be a nice to have.

**Comment by mcollina** [comment]
Why not? Seems harmless and nice.
Il giorno lun 19 gen 2015 alle 22:15 Jarrett Cruger <
notifications@github.com> ha scritto:

**Comment by jcrugzz** [comment]
@mcollina I agree :). Was just illuminating what works currently

**Comment by ralphtheninja** [comment]
Errors could be a separate module :)

**Comment by ralphtheninja** [comment]
@timoxley https://github.com/rvagg/node-levelup/pull/312 You could knock up a PR exposing it on the db object! :)

**Comment by juliangruber** [comment]
there's level-errors now as well :)
