### ISSUE TITLE
Can't get this running I keep getting LOCK

### ISSUE THREAD

**Issue by etiennea** [Level/levelup#219]
events.js:72
        throw er; // Unhandled 'error' event
              ^
OpenError: IO error: lock test/LOCK: Resource temporarily unavailable
    at /Users/me/Documents/Github/test/node_modules/level/node_modules/level-packager/node_modules/levelup/lib/levelup.js:114:34

**Comment by chovy** [comment]
I am having same issue. It seems two different processes cannot access the same db at the same time.
