### ISSUE TITLE
Expose statusCode on NotFoundError

### ISSUE THREAD

**Issue by mpareja** [Level/levelup#221]
I'll completely understand if you reject this issue because it involves interoperability with other projects.

The `NotFoundError` class is currently exposing a `status` property which is set to 404. This does not play nice with Restify's expectation of a `statusCode` property.  I believe - though I haven't verified -  that express uses `status`.

While I just want this to play nicely with other modules, one could argue that using `statusCode` is more congruent with `http.ServerResponse.statusCode` in core.

**Comment by juliangruber** [comment]
we have this already
