### ISSUE TITLE
0.19 tracking

### ISSUE THREAD

**Issue by rvagg** [Level/levelup#226]
* #207 Remove write-stream - really want to get this happening but it needs a level-fstream so we don't have to completely remove the functional tests.
 * Work with LevelDOWN@0.11 after we start allowing empty values, needs tests at a minimum.
 * Switch to documenting gt/lt/gte/lte instead of start/end, we're just waiting on level.js to support this so if someone has some time to put in to making it pass those tests then **please help** see maxogden/level.js#19 (cc @maxogden)

**Comment by juliangruber** [comment]
0.19 is out :)
