### ISSUE TITLE
delete a range

### ISSUE THREAD

**Issue by Raynos** [Level/levelup#23]
Having a function for

```
db.del({
    start: "a"
    , end: "b"
})
```

Would be useful.

Use-case here is to have mechanism to purge old data mainly

```
db.del({
    start: "name:"
    , end: "name:someTs"
})
```

**Comment by dcousens** [comment]
Is the best way to do this using

``` js
db.batch()
   .del(...)
   .del(...)
   .del(...)
   .del(...)
   .del(...)
   ...
```

**Comment by fergiemcdowall** [comment]
Range delete would be nice functionality, and it would also provide some symmetry with `gt`/`gte`/`lt`/`lte` in `.createReadStream()`.

Thinking out loud here: it would be great if you could read ranges or specified keys. For example:

`db.createReadStream({keys: ['id1'', 'id3', 'id16']})`

`db.del({keys: ['id1'', 'id3', 'id16']})`

`db.del({gte: 'id2', lte: 'id5'})`
