### ISSUE TITLE
level-codec: refactor out encodings? <thinkingoutloud>

### ISSUE THREAD

**Issue by dominictarr** [Level/levelup#232]
I'm working on a rewrite of level-sublevel.

The new rewrite will work with binary keys, and avoid the parasitic inheritance ("monkey patching" an instance) that was in the early versions. And all in all, make sublevel a more mature thing that integrates with levelup in a better way.

It'll also support the main new levelup aspects, like `lt, lte, gt, gte` and will assume there is no writestream. instead of changing `levelup#ReadStream` instances, it's gonna export an `leveldown#Iterator`, and then wrap that in a `ReadStream`

The nicest way to do this would be to just create a modified leveldown for each sublevel, and wrap that in a levelup instance - then sublevel will just have to create a leveldown api, and will have all the levelup features because it will just use that code directly.

there are some small changes that would I'd have to make to levelup though,
I wouldn't need to add any sublevel features, just add a few hooks that would make it easier to implement sublevel.

Basically, `LevelUp` and `ReadStream` would need to be separated from the encodings & options. sublevel needs to encode the bucket which any particular key falls into separately from what ever encoding that sublevel uses.

I'm not 100% certain how this would work yet, but it would basically entail having an `Options` object which managed the key/value encoding and other options and this would be passed to `LevelUp` and `ReadStream`.

The levelup code will probably end up looking very much like how it looks now,
except that you'll be able to pass the `util` variable in (allowing custom encoding strategies) instead of loading that from the `lib` folder directly.

I have a prototype of the sublevel refactor going on in the [v6](https://github.com/dominictarr/level-sublevel/tree/v6) branch, but it will change a bit to work with levelup properly.

**Comment by juliangruber** [comment]
this has been done :)
