### ISSUE TITLE
Allow for deep stack tracing

### ISSUE THREAD

**Issue by KenanSulayman** [Level/levelup#237]
Hi,

our codebase is growingly complex and just recently reached 303 Thousand lines of code. Within that codebase, we have 1397 calls to LevelDB at the time being — including ReadStreams, gets, puts and deletes.

We have a system in place that sends out a stack trace of every exception to every developer who is responsible for a particular module.

Every now and then, there's an issue when we introduce a new feature: a reference breaks. This isn't much of a problem since we usually have routines in place that take care of bad references - however, sometimes something like this happens:

	Cannot read property 'info' of undefined

	TypeError: Cannot read property 'info' of undefined
	    at *redacted*:407:100 <= library taking care of a callback
	    at *redacted*:129:25  <= location of callback
	    at *redacted*/node_modules/.../node_modules/levelup/lib/levelup.js:205:7

And here's the deal: can we allow deep stack traces somehow with Level to trace back what route the user took to reach that particular place?

Thanks

**Comment by juliangruber** [comment]
@KenanSulayman did `trycatch` work for you?

**Comment by KenanSulayman** [comment]
As far as I remember.. unfortunately it didn't. The stack-trace is simply lost when our callback (which is passed to level#get) is called from native code.

**Comment by juliangruber** [comment]
ok, as far as i understand we can close this then, feel free to reopen if you think this is still an issue
