### ISSUE TITLE
Cascading cache invalidation

### ISSUE THREAD

**Issue by andrewdeandrade** [Level/levelup#239]
So I was talking with dominictarr over twitter and on some github issues about a problem I'm trying to solve and he suggested that the best place to discuss it is over here in the levelup repo issues (even though it's not really an issue with the library itself).

I have a lot of values I want to cache and there is a dependency relationship between cached values. For example, when I cache value A, I then take that value and cache values B, C, and D, which may or may not be on the same "table" (i.e. sublevel). Later, if the value of A changes I want to be able to be at the very least about to invalidate B, C, and D and suffer cache misses next time B, C and D are requested, or better yet able to update the values of B, C and D based on the new value of A. 

This is just one level of caching. I'd like to be able to set up a tree describing the relationships between values and the getters to use to update the values. 

Furthermore, I'm not totally sure of the performance costs of get versus put operations in LevelUp. Assuming few dependent values (B, C and D) change, is it better to `get` a value, compare to the new value and not update it if nothing has changed or is it better to just calculate the new value and update the db whether or not the value has changed. I assume the former approach would be better since it wouldn't need to hold a lock.

I have a couple of ideas on how to tackle this, but before I go forward with my plans, i wanted to see if anyone else had already encountered this need and could provide some advice or point me to the most useful projects to help me accomplish this (like level-trigger)

**Comment by juliangruber** [comment]
is this discussion still going on?
