### ISSUE TITLE
idea: lazy open

### ISSUE THREAD

**Issue by dominictarr** [Level/levelup#252]
in some cases, it would be useful to not actually try and open the database unless the user actually does a read. In particular, when leveldb is part of a command line tool, there may be some operations where the database is not auctually necessary, and so opening the database may hold the process open unnecessaryily, especially if the database is largish and you have a spinning disk, not an ssd.

Since we already have buffering operations, this may be easy to add.
I don't think we should jump through any hoops to add this, but it could be a good optimization
if it's easy.

**Comment by juliangruber** [comment]
wrote this: https://github.com/Level/lazy-open

now just need to make levelup more flexible to work with this
