### ISSUE TITLE
Can't browserify latest version 0.18.5

### ISSUE THREAD

**Issue by JamesKyburz** [Level/levelup#254]
This is because bl has been added as a dependency, and the published bl@0.8.0 is missing stream-browserify dependency (which you have already fixed in master).

Could you please new versions?

➜  node-playground  npm ls levelup
playground@0.0.0 node-playground
├─┬ level@0.18.0
│ └─┬ level-packager@0.18.0
│   └── levelup@0.18.3
├─┬ level-browserify@0.18.1 extraneous
│ └─┬ level-packager@0.18.0
│   └── levelup@0.18.2
└── levelup@0.18.5

npm ERR! extraneous: level-browserify@0.18.1 node-playground/node_modules/level-browserify
npm ERR! not ok code 0
➜  node-playground  browserify -r levelup
Error: module "readable-stream" not found from "node-playground/node_modules/levelup/node_modules/bl/bl.js"

**Comment by juliangruber** [comment]
closing since this works
