### ISSUE TITLE
buffers turning into strings on the browser

### ISSUE THREAD

**Issue by calvinmetcalf** [Level/levelup#262]
doing valueEncoding: binary with level-js and inserting a typed array and then immediately getting it returns a string http://requirebin.com/?gist=9c331fd2fa400f47b786 issue seems to be here looks like level-js is returning a Uint8Array http://requirebin.com/?gist=21a0c419c1d807539d4d but this line https://github.com/rvagg/node-levelup/blob/master/lib/util.js#L63 is overriding the valueEncoding

**Comment by vweevers** [comment]
This hasn't been an issue for a while now. Encodings are no longer in levelup, `abstract-leveldown` got `_serializeValue`, and we have continuous browser tests (with buffers) for both `memdown` and `level-js`. It's solid.
