### ISSUE TITLE
How can I improve these keys?

### ISSUE THREAD

**Issue by ghost** [Level/levelup#308]
Hello. Hopefully the `node-levelup` issues board isn't an inappropriate place to ask a beginners question. I don't have a Google account to write on the Google group, the IRC channel is often idle and I couldn't find anywhere else to ask. Apologies in advance if there's a more appropriate place for it.

I'm starting to build my first web app backed by `node-levelup` and I'm curious to know whether the way I'm structuring my keys could be better. Things like, is there a better way to structure them so I might have a wider of variety of things to query using `createReadStream`? Currently I don't think I'd be able to query things like, the last 10 channels or posts from _all_ users, only a specific user. I could create another `post!all` or `channel!all` section for that, but I'm wondering if there's a way to pull that off with better key structure instead?

A note:
- When 'deleting' something, I don't want to remove it entirely, but instead, store it in another corner of the database that isn't accessible to any API endpoints, thus I've used the batch operations to remove from one spot and add to another. 

What can I do better?

``` javascript
// Create a user
db.put('user!sally', ...)

// Edit user settings
db.put('user!sally', ...)

// Delete user
db.batch([
  {type: 'del', key: 'user!sally'},
  {type: 'put', key: 'del!user!sally', ...}
])

// Create a channel
db.put('channel!sally!nature', ...)

// Edit a channel
db.put('channel!sally!nature', ...)

// View a channel
db.get('channel!sally!nature', ...)

// List a user’s channels
db.createReadStream({gt: 'channel!sally!', lt: 'channel!sally~')

// List all channels
db.createReadStream({gt: 'channel!', lt: 'channel~')

// Delete a channel
db.batch([
  {type: 'del', key: 'channel!sally!nature'},
  {type: 'put', key: 'del!channel!sally!nature', ...}
])

// Create a post
db.put('post!sally!nature!<timestamp>!<uuid>', ...)

// View a post
db.get('post!sally!nature!<timestamp>!<uuid>', ...)

// List all posts on a channel
db.createReadStream({gt: 'post!sally!nature!', lt: 'post!sally!nature~'})

// List last 10 posts on a channel
db.createReadStream({gt: 'post!sally!nature!', lt: 'post!sally!nature~', reverse: true, limit: 10})

// Delete a post
db.batch([
  {type: 'del', key: 'post!sally!nature!<timestamp>!<uuid>'},
  {type: 'put', key: 'del!post!sally!nature!<timestamp>!<uuid>', ...}
])
```

**Comment by ralphtheninja** [comment]
First of all you could start using `level-sublevel` which will take care of the namespacing for you, e.g.

```js
var level = require('level')
var sublevel = require('level-sublevel')
var db = sublevel(level('./db'))

var users = db.sublevel('users')
users.put('sally', {}, ..)

var channels = db.sublevel('channels')
var sallysChannels = channels.sublevel('sally')
channels.put('nature', {}, ...)

sallysChannels.createReadStream().on('data', function (data) {})
```

**Comment by cdroms** [comment]
This is true! I do feel comfortable writing out the entire keys, but I guess this wouldn't hurt either :)
Would you have any suggestions regarding structure of the keys themselves?

**Comment by ralphtheninja** [comment]
They look ok to me. But I'd be curious if anyone else has input on this. Key space is important and something that I'd like to see discussed more.

Also you can use [`level-move`](https://github.com/juliangruber/level-move) for your "delete" batching.

**Comment by cdroms** [comment]
`level-move`! Nice little neat abstraction there, thanks for pointing that out :)

I would agree that, from a beginner's perspective, more discussion around LevelDB key spacing strategy would be very useful. Understanding the way in which keys are stored and then how to query a certain range was fairly easy to get my head around, but then nutting out a nice key structure which gives you query flexibility later on when you need it is much tricker.

That being said, some things you require don't become obvious until much much later when it's harder to change the database.
