### ISSUE TITLE
1.0.0 status and prerelease

### ISSUE THREAD

**Issue by mcollina** [Level/levelup#330]
What's the status of 1.0.0?
I think we should get out another release before that, this repo had a lot of changes that are not released yet.

**Comment by ralphtheninja** [comment]
@juliangruber and I discussed if we should release a `levelup-next` module so we can try it out before releasing it

**Comment by mcollina** [comment]
how about releasing it with a `next` NPM tag (`npm publish . --tag=next`)? I think that's the preferred approach, so people can install `levelup@next`. I use that feature a lot :).

**Comment by ralphtheninja** [comment]
Aah yes that was what Julian meant :)

**Comment by juliangruber** [comment]
@ralphtheninja are you gonna? :)

**Comment by ralphtheninja** [comment]
Sure! :)

```
$ npm publish . --tag=next
+ levelup@1.0.0-0
```

```
$ npm i levelup@next
levelup@1.0.0-0 node_modules/levelup
├── prr@0.0.0
├── xtend@3.0.0
├── level-codec@5.5.0
├── semver@2.3.2
├── level-errors@1.0.3 (errno@0.1.2)
├── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
└── deferred-leveldown@0.3.0 (abstract-leveldown@0.12.4)
```

**Comment by ralphtheninja** [comment]
Hmm. `deferred-leveldown@0.3.0` uses `abstract-leveldown@0.12.4` which feels a bit old. I believe `leveldown` uses `2.1.0` now.

**Comment by ralphtheninja** [comment]
Scratch my previous comment, see https://github.com/Level/levelup/pull/332

**Comment by ralphtheninja** [comment]
@mcollina I'm recycling this issue! ;)

So we're at a `levelup@next` release pointing to tag `v1.0.0-5` which makes it the 6th pre-release.

@juliangruber What's the status of the `use/level-iterator-stream` branch? Did the prevent gc thing go into `level-iterator-stream`?

**Comment by juliangruber** [comment]
it went into abstract-leveldown, which is the right place to fix it. and that branch landed :) https://github.com/Level/levelup/blob/master/lib/levelup.js#L359

**Comment by ralphtheninja** [comment]
@juliangruber Good. I'm cleaning up that branch then.

**Comment by ralphtheninja** [comment]
My gut feeling tells me we can release `1.0.0` now. So +1 from me. Can we establish some kind of system for major releases? E.g. at least +4 in total?

**Comment by rvagg** [comment]
do eeet

**Comment by juliangruber** [comment]
+1 +1 +1 +1 i hope that's enough :)

**Comment by jcrugzz** [comment]
+1

**Comment by ralphtheninja** [comment]
```
$ npm publish
+ levelup@1.0.0
```

**Comment by juliangruber** [comment]
:tada: WOOP WOOP
