### ISSUE TITLE
Error with level on docker

### ISSUE THREAD

**Issue by Uhsac** [Level/levelup#340]
Hi,
I'm using level in one of my app, it work nicely when I run it on my mac using nodejs v0.12.2 but when I run it in Docker using the official node image with v0.12.2 I have this error when I launch the app.

```
scrap_1 | /app/node_modules/level/node_modules/leveldown/node_modules/bindings/bindings.js:83
scrap_1 |         throw e
scrap_1 |               ^
scrap_1 | Error: /app/node_modules/level/node_modules/leveldown/build/Release/leveldown.node: invalid ELF header
scrap_1 |     at Error (native)
scrap_1 |     at Module.load (module.js:355:32)
scrap_1 |     at Function.Module._load (module.js:310:12)
scrap_1 |     at Module.require (module.js:365:17)
scrap_1 |     at require (module.js:384:17)
scrap_1 |     at bindings (/app/node_modules/level/node_modules/leveldown/node_modules/bindings/bindings.js:76:44)
scrap_1 |     at Object.<anonymous> (/app/node_modules/level/node_modules/leveldown/index.js:1:99)
scrap_1 |     at Module._compile (module.js:460:26)
scrap_1 |     at Object.Module._extensions..js (module.js:478:10)
scrap_1 |     at Module.load (module.js:355:32)
soccerscrap_scrap_1 exited with code 1
```

I search where the error can come from but I don't find anything

Thanks for your help.

**Comment by ralphtheninja** [comment]
@Uhsac What version of `levelup` is this? Can it be the case that you have built the docker image for one system and running it on another system?

**Comment by Uhsac** [comment]
> What version of levelup is this?
I have this in my package.json : "level": "^0.19.1"

> Can it be the case that you have built the docker image for one system and running it on another system?
Hum I don't think so, I'm using docker-machine and docker-compose to run my app so the image build and run in the same system. I tried to launch it in boot2docker and on a digital ocean droplet.

Here is my app https://github.com/Uhsac/SoccerScrap if you want to have a look.

**Comment by ralphtheninja** [comment]
@Uhsac When building the image, do you use the same version of node?

**Comment by Uhsac** [comment]
> When building the image, do you use the same version of node?

Yes I'm using the latest node docker image which using node v0.12.2, you can find the dockerfile for this node image here https://github.com/joyent/docker-node/blob/413687b73f1f3d43286bfda1ea8008509538d8bd/0.12/Dockerfile

**Comment by mcollina** [comment]
Are you ignoring the node_modules folder when building your image (in
.dockerignore), and then are running npm install in the Dockerfile?

Il giorno sab 16 mag 2015 alle ore 13:54 Lars-Magnus Skog <
notifications@github.com> ha scritto:

**Comment by Uhsac** [comment]
> Are you ignoring the node_modules folder when building your image (in
.dockerignore), and then are running npm install in the Dockerfile?

No ! I will give it a try, and I think it could be the problem ! (I'm using npm install in dockerfile but maybe it is overwritten when I insert my code)

**Comment by ralphtheninja** [comment]
Something tells me the build step is not made on the same system that it's running on. This is what the error tells us. The binaries have been built on a different system. Unfortunately I'm not familiar with how docker-machine etc works.

**Comment by Uhsac** [comment]
@mcollina Thanks a lot ! It worked ! I didn't know the existence of the .dockerignore file !
Thanks @ralphtheninja for your help !

**Comment by ralphtheninja** [comment]
@Uhsac Please push your updated code so I can have a look and learn something myself ;)

**Comment by Uhsac** [comment]
@ralphtheninja Done :)

**Comment by ralphtheninja** [comment]
It's still not clear to me what's going on and what happens when.

**Comment by Uhsac** [comment]
When Docker build the image following my Dockerfile it add the package.json in the container and run npm install : 
```
ADD package.json /app/
RUN npm install
```
So now I have a node_modules in my container, and after that I add all my current directory in the container :
```
ADD . /app/
```
And here is the problem because in my current directory I already had a node_modules directory so when I add it I overwrite the node_modules directory that is in the container.

**Comment by ralphtheninja** [comment]
Aaah gotcha. Makes total sense now. Thanks!

Please close this issue when you feel you're happy.

**Comment by Uhsac** [comment]
Thanks a lot again !
