### ISSUE TITLE
remove compression tests

### ISSUE THREAD

**Issue by juliangruber** [Level/levelup#343]
..and move them to leveldown's testsuite, since not all backends support that

**Comment by juliangruber** [comment]
https://github.com/Level/leveldown/pull/181

**Comment by ralphtheninja** [comment]
I can take this tomorrow as an easy start :)

**Comment by ralphtheninja** [comment]
@juliangruber How about a PR into `v2` branch? It'll land in master when we decide to merge.

**Comment by juliangruber** [comment]
@ralphtheninja too late :P https://github.com/Level/levelup/pull/348

**Comment by ralphtheninja** [comment]
*grins*
