### ISSUE TITLE
remove .errorIfExists, .createIfMissing

### ISSUE THREAD

**Issue by juliangruber** [Level/levelup#344]
too backend specific

**Comment by juliangruber** [comment]
or what do other collaborators think?

**Comment by ralphtheninja** [comment]
+1 `.createIfMissing` only really makes sense for leveldown.

**Comment by juliangruber** [comment]
and I haven't seen a use case for `.errorIfExists`

**Comment by juliangruber** [comment]
#349

**Comment by ralphtheninja** [comment]
Done in `2.x` branch
