### ISSUE TITLE
Loosen version checking to match npm?

### ISSUE THREAD

**Issue by mhart** [Level/levelup#351]
Just had a user post this:

https://github.com/mhart/kinesalite/issues/13

Because my package.json had levelup at `^1.1.0` and leveldown at `^1.0.6` (both added by `npm install --save`) – which certainly worked fine when they were added, and up until recently when leveldown bumped its minor.

Unfortunately levelup uses a stricter checking mechanism to match against its expected leveldown version (`~1.1.0`) so as soon as leveldown bumped its minor version, npm installs started breaking.

Is there a reason levelup needs to be so strict in its check? Wouldn't it be better (for certain values of "better") to allow levelup to use newer leveldowns as long as they're backwards compatible?

Having installs break on a minor bump is a bit of a bummer.

**Comment by juliangruber** [comment]
for levelup@2 we removed this check completely. for now, since the default behavior of npm is to use `^` instead of `~`, I'm voting (as @ralphtheninja suggested in chat) for switching the dev dependency to use `^`.

@rvagg what do you think?

**Comment by juliangruber** [comment]
oh, is there a reason you're not just using the `level` package?

**Comment by mhart** [comment]
@juliangruber yeah, leveldown is an optional dependency (I use MemDOWN if it's not available/specified)

**Comment by ralphtheninja** [comment]
@mhart Sorry for the inconvenience. I don't mind being less restrictive in levelup's package.json and we can get a new version out quick. Just want to hear what others say :)

/cc @Level/owners

**Comment by mafintosh** [comment]
i'm +1 on switching to `^`. the same goes for the level package

**Comment by ralphtheninja** [comment]
@mafintosh level is somewhat different since the level api is level-packager api (levelup api + repair + destroy ) + leveldown, so new minors to leveldown should affect version of level see https://github.com/Level/level/issues/27

But levelup does not depend on leveldown and therefore we can be less restrictive

Feel free to chip in on that thread if you disagree :)

**Comment by rvagg** [comment]
I'll opt out of this one, I'm anti `^` for pretty much every case but I'll save you another rant

**Comment by mcollina** [comment]
I'm in for loosen this too.
Il giorno mer 3 giu 2015 alle 04:37 Rod Vagg <notifications@github.com> ha
scritto:

**Comment by soldair** [comment]
i was pretty sure this was an @rvagg troll thread at first =P

**Comment by shotlom** [comment]
I wanted to give it a try but no love for a new user out of the box:

```
/Users/chr/dev/leveldb-test/node_modules/levelup/lib/util.js:42
    throw new LevelUPError(
          ^
LevelUPError: Installed version of LevelDOWN (1.2.2) does not match required version (~1.1.0)
    at getLevelDOWN (/Users/chr/dev/leveldb-test/node_modules/levelup/lib/util.js:42:11)
    at LevelUP.open (/Users/chr/dev/leveldb-test/node_modules/levelup/lib/levelup.js:114:37)
    at new LevelUP (/Users/chr/dev/leveldb-test/node_modules/levelup/lib/levelup.js:87:8)
    at LevelUP (/Users/chr/dev/leveldb-test/node_modules/levelup/lib/levelup.js:47:12)
    at Object.<anonymous> (/Users/chr/dev/leveldb-test/app.js:5:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

```

**Comment by ralphtheninja** [comment]
@shotlom How do you get this error? What does your package.json look like?

**Comment by ralphtheninja** [comment]
@mhart I just published `levelup@1.2.0`. Mind trying it out?

**Comment by mhart** [comment]
Brilliant – works perfectly for me.

Should fix issues with anyone doing `npm install levelup leveldown` too.

Thanks @ralphtheninja !

**Comment by shotlom** [comment]
It's working for me now also! I was installing with ```npm install levelup leveldown```
