### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by grudzinski** [Level/levelup#356]
This will cause Segmentation fault (core dumped):

```bash
node -e 'require("leveldown")("test").get("boom", console.log)'
```

I know, ```open()``` call is missed.

**Comment by juliangruber** [comment]
leveldown is quite raw so this is expected behavior. levelup in contrast will handle the states for you and not cause this issue.

See:

```bash
node -e 'require("levelup")("test").get("no boom", console.log)'
```
