### ISSUE TITLE
[question] Is it possible to get values as streams?

### ISSUE THREAD

**Issue by fergiemcdowall** [Level/levelup#357]
Say you have really big values (strings, arrays) in your levelup index, and you only want to read the first few elements of the value. Would it be possible to get a readStream of the value such that you didn't have to load the _whole_ thing just to get the first part of it?

**Comment by ralphtheninja** [comment]
You could do a `createReadStream()` and pipe that to `JSONStream` or something like that.

**Comment by rvagg** [comment]
If you're talking about the individual values being very large then the answer is _no_, they have to be loaded and passed to JS as a whole, there's no way around that. If you're talking about having a lot of them then yes, `createReadStream()` does them piece by piece so doesn't waste (much).

You might want to look at @juliangruber's https://github.com/juliangruber/level-store as an option for dealing with large data elements, ideally you shouldn't be storing them in single values.

**Comment by fergiemcdowall** [comment]
OK! Thanks for the answer :)

**Comment by ralphtheninja** [comment]
@rvagg is obviously correct here. Sorry for misleading information from my side :)
