### ISSUE TITLE
inconsistent createReadStream behavior after put

### ISSUE THREAD

**Issue by timkuijsten** [Level/levelup#358]
This might be related to https://github.com/Level/levelup/pull/128. While testing my implementation that uses levelup I'm doing a lot of put and batch operations and open an iterator afterwards to test the inserted objects. Most of the times everything that I've put is returned by the iterator, but sometimes it misses some of the last items.

I've created a small test that shows this problem, as well as a weird thing that when using a buffer with non-random content, everything goes well, but as soon as some random space is allocated, the iterator starts missing some written objects after some iterations.

```
$ cat test.js
'use strict';

var tmpdir = require('os').tmpdir;

var rimraf = require('rimraf');
var level = require('level');

var db;
var dbPath = tmpdir() + '/test_iterator';

// open database
function start(done) {
  rimraf(dbPath, function(err) {
    if (err) { throw err; }
    level(dbPath, { keyEncoding: 'binary', valueEncoding: 'binary' }, function(err, _db) {
      if (err) { throw err; }
      db = _db;
      done();
    });
  });
}

function after(done) {
  done = done || function() {};
  db.close(function(err) {
    if (err) { throw err; }
    rimraf(dbPath, done);
  });
}

// write a one byte key, then iterate, do this 20 times
function readAfterWriteTest(done) {
  var i = 0;
  function writeRead() {
    i++;
    // strategy 1 where the iterator never misses any written items:
    //db.put(new Buffer([i]), null, { sync: true }, function(err) {
    // strategy 2 where the iterator sometimes misses some written items:
    db.put(new Buffer(1), null, { sync: true }, function(err) {
      if (err) { throw err; }
      var s = db.createKeyStream();
      var j = 0;
      s.on('data', function() { j++; });
      s.on('close', function(err) {
        if (err) { throw err; }
        console.log('missed %d', (i - j).toString());
        if (i < 20) {
          writeRead();
        } else {
          done();
        }
      });
    });
  }

  writeRead();
}

start(function() {
  readAfterWriteTest(after);
});
```

Strategy 1 using new Buffer([i]) where the iterator never misses any written items:
```
$ node test.js
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
```

Strategy 2 using new Buffer(1) where the iterator sometimes misses some written items:
```
$ node test.js
missed 0
missed 0
missed 0
missed 0
missed 0
missed 1
missed 1
missed 1
missed 1
missed 1
missed 2
missed 3
missed 3
missed 3
missed 3
missed 4
missed 5
missed 6
missed 7
missed 7
```

when repeating the test with new Buffer(1) the missed items fluctuate. I guess this is because even though the callback is only called after the contents have been flushed to disk (since sync is used) the snapshot created by createReadStream still somehow predates these new contents?

**Comment by timkuijsten** [comment]
ps. tested with node 0.10.31, 0.12.7 and iojs 2.5.0.

**Comment by ralphtheninja** [comment]
@timkuijsten Can you make sure that the db is fully open first?

E.g. instead of doing

```js
db = level(dbPath, { keyEncoding: 'binary', valueEncoding: 'binary' });
done();
```

Do something like:

```js
level(dbPath, { keyEncoding: 'binary', valueEncoding: 'binary' }, function (err, _db) {
  db = _db;
  done();
});
```

It might not make a difference, but I just want to rule out if it has anything to do with the open state of the db or not.

**Comment by timkuijsten** [comment]
Done as you've said + added two extra error checks. Changed the code mentioned above as well. No changes in behavior unfortunately.

````
$ gd test.js
diff --git a/test.js b/test.js
index a9a6110..f65c22a 100644
--- a/test.js
+++ b/test.js
@@ -12,8 +12,11 @@ var dbPath = tmpdir() + '/test_iterator';
 function start(done) {
   rimraf(dbPath, function(err) {
     if (err) { throw err; }
-    db = level(dbPath, { keyEncoding: 'binary', valueEncoding: 'binary' });
-    done();
+    level(dbPath, { keyEncoding: 'binary', valueEncoding: 'binary' }, function(err, _db) {
+      if (err) { throw err; }
+      db = _db;
+      done();
+    });
   });
 }
 
@@ -34,10 +37,12 @@ function readAfterWriteTest(done) {
     //db.put(new Buffer([i]), null, { sync: true }, function(err) {
     // strategy 2 where the iterator sometimes misses some written items:
     db.put(new Buffer(1), null, { sync: true }, function(err) {
+      if (err) { throw err; }
       var s = db.createKeyStream();
       var j = 0;
       s.on('data', function() { j++; });
       s.on('close', function(err) {
+        if (err) { throw err; }
         console.log('missed %d', (i - j).toString());
         if (i < 20) {
           writeRead();
```

```
$ node test.js
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0
missed 0                            
missed 0
missed 0
missed 1
missed 1
missed 2
missed 2
missed 2
missed 3
```

**Comment by jcrugzz** [comment]
The inconsistency seems to have to do with using the same key. Im not sure how the internals work in this case with snapshots but it kind of makes sense that this COULD happen with it being the same key.

**Comment by timkuijsten** [comment]
@jcrugzz it's not the same key, creating a new buffer of a random size allocates some random memory, see this adapted test.
```
$ gd test.js 
diff --git a/test.js b/test.js
index f65c22a..e663e96 100644
--- a/test.js
+++ b/test.js
@@ -36,7 +36,9 @@ function readAfterWriteTest(done) {
     // strategy 1 where the iterator never misses any written items:
     //db.put(new Buffer([i]), null, { sync: true }, function(err) {
     // strategy 2 where the iterator sometimes misses some written items:
-    db.put(new Buffer(1), null, { sync: true }, function(err) {
+    var b = new Buffer(1);
+    process.stdout.write(JSON.stringify(b) + '\t');
+    db.put(b, null, { sync: true }, function(err) {
       if (err) { throw err; }
       var s = db.createKeyStream();
       var j = 0;
```
```
$ node test.js 
{"type":"Buffer","data":[0]}    missed 0
{"type":"Buffer","data":[210]}  missed 0
{"type":"Buffer","data":[32]}   missed 0
{"type":"Buffer","data":[1]}    missed 0
{"type":"Buffer","data":[255]}  missed 0
{"type":"Buffer","data":[16]}   missed 0
{"type":"Buffer","data":[70]}   missed 0
{"type":"Buffer","data":[31]}   missed 0
{"type":"Buffer","data":[40]}   missed 0
{"type":"Buffer","data":[192]}  missed 0
{"type":"Buffer","data":[0]}    missed 1
{"type":"Buffer","data":[0]}    missed 2
{"type":"Buffer","data":[72]}   missed 2
{"type":"Buffer","data":[112]}  missed 2
{"type":"Buffer","data":[203]}  missed 2
{"type":"Buffer","data":[32]}   missed 3
{"type":"Buffer","data":[1]}    missed 4
{"type":"Buffer","data":[255]}  missed 5
{"type":"Buffer","data":[1]}    missed 6
{"type":"Buffer","data":[73]}   missed 6
```

**Comment by jcrugzz** [comment]
Ahh interesting. does this only happen when using `Buffer`'s as keys? Do you explicitly set the `keyEncoding` on the `levelup` instance? Id like to see if that changes the behavior at all.

**Comment by doowb** [comment]
It looks like the "missed" count only increases when the data in the new Buffer is not unique. Wouldn't this mean duplicate keys are being 'put'? causing `i` and `j` to differ? I might be missing something with how `new Buffer(1)` is working.

**Comment by timkuijsten** [comment]
@doowb I guess you're right! this test case is not representative for the problems I experience when testing my own [app](https://github.com/Netsend/mastersync/blob/level/test/lib/mocha/tree.js#L2182-L2186). When I run those tests the count in [#L2182](https://github.com/Netsend/mastersync/blob/level/test/lib/mocha/tree.js#L2186) is most of the times 3 like expected, but sometimes 2.

I'll see if I can create another simpler test to reproduce.

**Comment by mcollina** [comment]
Some questions:

* does this problem only happen with `sync: true`?
* adding a `setImmediate` does solve the problem?

Would you mind also checking with an older version, i.e. v0.19? (This won't probably run on latest iojs/node)

**Comment by timkuijsten** [comment]
> does this problem only happen with sync: true?

no, with both sync: true and sync: false.

> adding a setImmediate does solve the problem?

no, not even a setTimeout 50.

> Would you mind also checking with an older version, i.e. v0.19? (This won't probably run on latest iojs/node)

I've tested it with levelup 0.19.0 and leveldown 0.10.5 on node 0.12.7 and the last written item still misses sometimes in the test following.

It looks like this is the opposite of #128. I put an item and then open a read stream in which case I do expect the last putted item to appear in the read stream. Is this assumption wrong?

**Comment by mcollina** [comment]
Just a quick thing: `new Buffer(i)` returns a buffer of length `i` with random content. However that is not truly random: it's mostly filled by zeroes at the beginning of a program. So it might be a case where two keys collide?

**Comment by timkuijsten** [comment]
@mcollina that was definitely the case with the test that I submitted in this issue as @doowb pointed out, but that is not the case (or at least shouldn't, I'm verifying that as we speak) in the [test](https://github.com/Netsend/mastersync/blob/level/test/lib/mocha/tree.js#L2174-L2190) that triggers this issue now and then. So far I haven't been able to really pin-point it down..

**Comment by timkuijsten** [comment]
I did a test with writing 6 pseudo random buffers in a batch (with an increment in each buffer to avoid the earlier encountered duplication). After writing each batch I open a read stream and it counts every written item including the last batch, for 1000s of writes in a row, so I assume (again) that this bug is hidden somewhere in the complexities of my own code. If I can pinpoint it and that directs me to levelup, I'll reopen the issue. Thank you all for helping me in this, appreciate it.

**Comment by timkuijsten** [comment]
I think I've found my issue, see #359. I'm currently working around it by using a [semaphore](https://github.com/Netsend/mastersync/blob/17514b5d06c5dd55044a31f3f2fd07228b3f09e4/lib/tree.js#L764) that is checked in the close event and in the data event.
