### ISSUE TITLE
Problems installing on Windows 10

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [Level/levelup#360]
When I run `npm install levelup leveldown` on my windows 10 system, I get the following errors.

```
LINK : fatal error LNK1104: cannot open file 'libcpmt.lib' [H:\MEGA\Programming\ES\server\node_modules\leveldown\build \leveldown.vcxproj]
prebuild ERR! build `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "levelup" "leveldown"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.4.1 install: `prebuild --download`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the leveldown@1.4.1 install script 'prebuild --download'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --download
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     H:\MEGA\Programming\ES\server\npm-debug.log
```

[Here is a gist of the entire npm-debug.log](https://gist.github.com/stephan-nordnes-eriksen/5b8df40a257717a10a1e). 

What am I doing wrong? I believe I have all the prerequisites installed.

**Comment by ralphtheninja** [comment]
@stephan-nordnes-eriksen Mind trying to reduce this to just do `npm i leveldown --verbose` and copy/paste that output into a gist? It would also be helpful if you could post the output of these commands:

```
$ node -pe process.versions
$ node -pe process.arch
```

**Comment by stephan-nordnes-eriksen** [comment]
[output from verbose](https://gist.github.com/stephan-nordnes-eriksen/6efba82e40d1648903bb)

`node -pe process.versions
{ http_parser: '2.3',
  node: '0.12.7',
  v8: '3.28.71.19',
  uv: '1.6.1',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1p' }`

`node -pe process.arch
x64`

**Comment by ralphtheninja** [comment]
Ok, so this is related to no prebuilt binaries for `leveldown` for windows x64 and `prebuild` then falls back to a compile step and your system is not setup properly to build native modules.

**Comment by stephan-nordnes-eriksen** [comment]
I see. Sorry for slow responses. I actually went for nedb in sted because I did not have the time to deal with this now.
