### ISSUE TITLE
promise api

### ISSUE THREAD

**Issue by mfrost66** [Level/levelup#361]
Any opposition to adding promise support to the library?  It would be as "simple" as returning a promise if no callback param was defined.

**Comment by No9** [comment]
My first reaction is that should be in a separate repo and looking on npm I see https://www.npmjs.com/package/then-levelup exists already.
 
Also changing the API contract is not something I would enter into lightly due to potential impacts on other libraries as well as documentation etc.

**Comment by mfrost66** [comment]
Adding an option ({promises:true}) would avoid any behavior change

I've already promisified my use of levelup, just wondering out loud if there was a specific reason it wasn't already done.  Do you all see the use of promises as marginal, or is there an expectation that each user will promisify the library themselves or thru 3rd party wrappers?

**Comment by juliangruber** [comment]
> It would be as "simple" as returning a promise if no callback param was defined.

that wouldn't always work as currently `db.put('foo', 'bar')` is valid and will emit an `"error"` event on `db` if the operation fails.

At this point in time the migration cost to an all promise levelup would overweigh the benefits, but in the future iff promises become the standard way of doing async work in node I can def. see us using them.

The problem with `({ promises: true })` is that it causes levelup to have a new api and not work with the current module ecosystem any more, so promisifing levelup with a custom lib is just as good.

You can always do something like:

```js
function MyModule(db){
  this.db = promisify(db);
  this.raw = db;
}
MyModule.prototype.foo = function(cb){
  this.db.get('foo').then(cb);
};
MyModule.prototype.bar = function(cb){
  callModuleThatRequiresRawLevelUp(this.raw);
};
```

I've been following that pattern when my applications are using something like `co` / generators.

I'm closing this, feel free for anyone to reopen if there's reasons to investigate promise use further.

**Comment by mfrost66** [comment]
>>>but in the future iff promises become the standard way of doing async work in node

it seems to me that promises are, in many ways, an attempt to solve the poor experience that was async programming in node using events

Given that promises & generators are part of the final ES6 and out-of-the-box in node, I was kind of thinking the future had already arrived! :)

**Comment by mfrost66** [comment]
Any chance of exposing Batch() so that I can promisify the prototype (for the chained version) instead of each instance?

**Comment by rvagg** [comment]
> it seems to me that promises are, in many ways, an attempt to solve the poor experience that was async programming in node using events

This is a common refrain but there are many of us who completely reject the premise that async programming has a "poor experience" and rather appreciate the callback and events model and find Promises to be too heavy-weight, have a very poor approach to error handling and are unnecessarily abstract. You can code equally garbage (possibly greater garbage) code with Promises as you can with callbacks so I see nothing compelling here.

As Promises can wrap callbacks, particularly with auto-wraping mechanisms available in most of the popular Promises libraries then adding it in the levelup core will simply be an exercise in expanding the API surface area that needs to be maintained by this team, which is something that most of us would like to avoid and goes against the _small-core_ philosophy that most of us hold dear. Just use something like then-levelup or write your own, it wouldn't be hard, if you come up with something particularly nice then you may even get a link in the README here for people looking for this option.

The only single compelling case I can see for adding Promises to levelup is when language primitives start relying on them. async await and WHAT-WG streams and .. whatever's going on in ES7 dreamland all seem to be embracing Promises as a required mechanism and if levelup finds itself in a position of not being able to work with these new primitives without exposing Promises then it'd be an easy argument to pursue here. But for now, this is just fluff for the sake of people who think "callback hell" is a thing and "promises hell" isn't.

**Comment by UltCombo** [comment]
@rvagg 

> have a very poor approach to error handling

Would you mind expanding on that?
IMHO, the error handling and composability are the main points of promises. The only problem with promises' error handling I see is that thrown errors in the final `catch` used to be ignored, but that's easily fixable with io.js >= 3/Node.js >= 4's `unhandledRejection` event, or in the userland side with libraries that implement a `.done()` method.

> ES7 dreamland 

Async/await is already implemented (experimentally) in the latest Windows Insider build's Edge. I'd say Async functions are pretty much a reality now, but I wouldn't give it a time frame -- ES2016 would most likely be rushing it, and I'm yet to see interest from the V8 side.

> particularly with auto-wraping mechanisms available in most of the popular Promises libraries then adding it in the levelup core will simply be an exercise in expanding the API surface area that needs to be maintained by this team

:+1: As long as the package's API can be easily promisified (e.g. `bluebird.promisifyAll`) there's no need to change right now. As for the API-surface area, if you ever intend to support Promises out of the box, then it would be better to kill off the callback API completely and thus maintain an uniform API with the same surface size.

**Comment by rvagg** [comment]
> As for the API surface area, if you ever intend to support Promises out of the box, then it would be better to kill off the callback API completely and thus maintain an uniform API with the same surface size

levelup is nothing special, there's no reason you can't do this now if you think it's so compelling, that's the beauty of npm and small modules, we get to compete on ideas, perhaps you can publish levelupper with a Promises API and it's so awesome that the userbase slowly drains away from levelup in its favour, no need to change levelup unless we want to inflict wholesale API change on the entire level* ecosystem, which isn't really the style of the core team here.

**Comment by UltCombo** [comment]
I'm not quite a level* user, was mostly just curious about your stand on promises' error handling. :smile_cat:

But regarding your point:

> perhaps you can publish levelupper

Wrapping libraries is most often done poorly. Duplicating work is most often a bad thing as well -- just this week I had to switch between **four** promise implementations/wrappers of a given library in order to find one that contains the minimum subset of features required for my use case.

Another point against wrapper libraries is that by adding one more dependency level you will be stuck with an outdated version of the underlying library when new major releases are published, until the wrapper library is updated to support it.

> no need to change levelup unless we want to inflict wholesale API change on the entire level* ecosystem, which isn't really the style of the core team here.

Makes sense.

**Comment by llambda** [comment]
Just some babbling on a Friday.

Promise wrapper can be done such that version dependencies are not a concern, here https://github.com/llambda/cassandra-prom ... is one approach I took ... of course there are downsides with this approach as well.

FWIW Bluebird gives you .asCallback function ( https://github.com/petkaantonov/bluebird/blob/master/API.md#ascallbackfunction-callback--object-options---promise ) so you can provide a Promise and callback API at the same time (of course, you then incur the cost of creating promises, so weigh that). FWIW I don't think the native promise API is good enough for use in projects as it's missing quite a lot of functions that bluebird provides.

FWIW https://github.com/neumino/rethinkdbdash provides a promise based api, and it's a dream to use. Especially with Bluebird.coroutine they are pretty nice to use. Bluebird gives a nice long async call "stacks", which for me at least I believe to have found more valuable than the performance hit incurred with promises. 

Personally I love promises, that said I agree with @rvagg don't think they should be in core for reasons keep core small and to ensure competition in the userspace for async mechanisms.

**Comment by mfrost66** [comment]
Given the ability to support promises without an API change or performance impact (don't create them if not requested), I'd assumed the reason wasn't technical and didn't know if it was philosophical or just that it hadn't been done.  I'm in the process of doing the work anyway, and was mostly just wanting to see if if there was a desire to add it back into this library.

Thanks for taking the time to respond, and also for the work to date.

**Comment by UltCombo** [comment]
Thanks for the insight, @llambda.

> Promise wrapper can be done such that version dependencies are not a concern

True, but only if you agree to at least one of these contracts:
- Take a generic enough approach that completely disregards the wrapped module's API (e.g. `bluebird.promisifyAll()`);
- Assume there will be no breaking changes in the wrapped library's API.

I see your package does a combination of both.

> FWIW I don't think the native promise API is good enough for use in projects as it's missing quite a lot of functions that bluebird provides.

True. The ES2015 Promises contain only the very core of the promises implementation. It is *supposed* to be extended in future ECMAScript editions, although I don't see any proposal to do so yet.

> for reasons keep core small

I believe the size is maintained as long as you ditch callbacks for promises. Of course, there's a bigger penalty that is getting your entire user base and level* stack to use promises.

In the other hand, @sindresorhus has decided to update all his packages removing callbacks and adding promise APIs. That means a major release of a few hundred packages at least, which is quite a bold move.

**Comment by mcollina** [comment]
It seems there should be an official levelup promise wrapper that we
maintain and care about. I also feel that levelup is almost done, and we
should include the warpper in level.
Il giorno sab 12 set 2015 alle 02:12 Fabrício Matté <
notifications@github.com> ha scritto:

**Comment by juliangruber** [comment]
> It seems there should be an official levelup promise wrapper that we
> maintain and care about.

I would be supportive of maintaining a promise implementation in the `level` organization. If we agree on that let's discuss this in a new issue.

> I also feel that levelup is almost done, and we
> should include the warpper in level.

Are you thinking of something like `var level = require('level/promise')`?

The main concern I have with an "official" levelup promise version is that it will cause pain for the ecosystem unless we can keep friction very low. People _will_ pass promised levelup instances to modules expecting a callback version, and vice versa.

Solutions come to my mind such as `var db = opts.db.callback()` / `var db = opts.db.promise()` to ensure you have the right version of levelup, but that would require us to have the promise version _inside_ levelup and not just level which I'm quite sure the level team won't be found of.

So I'm still -1 on an offical promise LevelUp.

What I can however see us doing is to suggest a promise module in the README but strongly warn about the issues one can run into.

**Comment by mcollina** [comment]
> Are you thinking of something like `var level = require('level/promise')`?

Yes. Or an official wrapper that we can pass level instances to, something like:

```js
var db  = requie('level')('mydb')
db = require('level-promise')(db)
```

What I am saying is that I am seeing more and more people asking for promise support across my modules and others. I will not use any of it, but I still think we should have an official way of doing that, so people could bring extensions on top of it. I just think this should be official, and we should take that into account for API breakages and evolution of the ecosystem. I am starting to see large-scale projects based on promises in my day-to-day job as well.

**Comment by juliangruber** [comment]
Well I guess the solution to drop optional callback support and use a lib to auto-return promises isn't too bad... Pouch is doing that as well, so pulling in @nolanlawson, how's that going for you?

**Comment by juliangruber** [comment]
And yeah I'm not ultra against an official promise lib, I'm just very concerned about the ecosystem. The same problems might arise though if we removed optional callbacks.

**Comment by mfrost66** [comment]
I have written and lightly tested an initial version of levelupAsync.  It extends the existing API with promise versions by creating *Async versions of callbacks methods - openAsync, putAsync etc.  It uses native promises and thus avoids requiring a promise library like [then-levelup](https://www.npmjs.com/package/then-levelup) mentioned above.  

I've attached the code here in case its useful as a baseline for an official module.

A couple of thoughts:
1. It might make sense just to integrate the methods into levelup directly as the amount of code would be minor
2. Assuming a separate levelupAsync module, the batch.write function should probably be exposed to simplify adding batch().writeAsync() and avoiding the clunkiness below accessing the prototype

```javascript
/** Extends 'levelup' with promise versions of the functions that take a callback

Async methods
  openAsync()
  closeAsync()
  getAsync()
  delAsync()
  putAsync()

  batch().writeAsync()
 */
'use strict';

var levelUp = module.exports = require('levelup');

// extend levelup with async methods
// use param specific versions used instead of generic function (requiring arguments manipulation)
//   to minimize performance impact
async0(levelUp.prototype,'open','close');
async2(levelUp.prototype,'get','del');
async3(levelUp.prototype,'put');

// hook batch to extend on first use since prototype is not accessible
levelUp.prototype._batch = levelUp.prototype.batch;
levelUp.prototype.batch = function(){
  // extend batch with async versions
  var batch = this._batch(); // access prototype via instance
  async0(batch.__proto__,'write');

  // restore original batch
  levelUp.prototype.batch = levelUp.prototype._batch;
  delete levelUp.prototype._batch;
  return this.batch.apply(this,arguments);
};

/** Create promise function with 0 params for all given function names
 * @param base {Object} the base object containing the source function(s)
 * @param funcName {...string} any number of function names.
 *    for each name, a promise version will be created by appending 'Async' to the given name */
function async0(base,funcName){
  Array.prototype.splice.call(arguments,1).forEach(function(name){
    base[name+'Async'] = function(){
      var db = this;
      var func = base[name];
      return new Promise(function(resolve,reject){
        func.call(db,function(err,value){ if( err ) reject(err); else resolve(value) }) })
    }
  })
}

/** 2 param version of {@link async0} */
function async2(base){
  Array.prototype.splice.call(arguments,1).forEach(function(name){
    base[name+'Async'] = function(key,value){
      var db = this;
      var func = base[name];
      return new Promise(function(resolve,reject){
        func.call(db,key,value,function(err,value){ if( err ) reject(err); else resolve(value) }) })
    }
  })
}

/** 3 param version of {@link async0} */
function async3(base){
  Array.prototype.splice.call(arguments,1).forEach(function(name){
    base[name+'Async'] = function(key,value,options){
      var db = this;
      var func = base[name];
      return new Promise(function(resolve,reject){
        func.call(db,key,value,options,function(err,value){ if( err ) reject(err); else resolve(value) }) })
    }
  })
}
```

**Comment by mattstyles** [comment]
Its an extension to the existing callback API so

```
var db = require( 'level' )( 'mydb' )
db = require( 'level/promise' )( db )

// or

db = require( 'level/async' )( db )
```

Similar to many other level wrappers right?

Maintains the flexible spirit of leveldb.

**Comment by stuartpb** [comment]
It's about a year later and non-Promise-based APIs are becoming increasingly difficult to work with in a modern ES6+ oriented, Promise-laden ecosystem (as @rvagg prognosticated) - any movement on this (at least adopting some library that would return, essentially, `require('promisify')(require('level'))`)?

**Comment by mcollina** [comment]
I'm ok with an official "leveup-as-promised" on top of this, as I was last year. I'm still against them on leveldown and levelup, and that will probably not change until there is API support for promises into node.js master branch. I don't see that happen soon.

**Comment by dominictarr** [comment]
oh hey, what you could do is generate the promise api from the multilevel mainfest. That lists which functions are streams and which are async, and is also relatively standardized.

https://github.com/dominictarr/level-manifest
https://github.com/juliangruber/multilevel

**Comment by juliangruber** [comment]
> I'm ok with an official "leveup-as-promised" on top of this, as I was last year. I'm still against them on leveldown and levelup, and that will probably not change until there is API support for promises into node.js master branch. I don't see that happen soon.

I agree, I'd be happy to maintain a promise layer under the level org.

**Comment by TimothyGu** [comment]
Has there been any updates on the promise layer idea?

**Comment by ralphtheninja** [comment]
> Has there been any updates on the promise layer idea?

Not really no.

**Comment by juliangruber** [comment]
With all that's going on right now I'd be happy to ship a promise layer in V2 of levelup's core

**Comment by mcollina** [comment]
I agree.

**Comment by stuartpb** [comment]
Looks like you're [just putting together the plan for v2](https://github.com/Level/levelup/milestone/1) - looking forward to a roadmap soon.

**Comment by zixia** [comment]
Looking forward to the promisified API of levelup, it will really be sweet. Thanks!

**Comment by ralphtheninja** [comment]
Merged into `2.x` branch.

**Comment by lianzhao** [comment]
[readme](https://github.com/Level/levelup/blob/master/README.md) pointed out that Promise api was ready.
But seems that it will be shipped with 2.x release?

**Comment by zixia** [comment]
@lianzhao You can install v2 by run:
```shell
npm install levelup@2.0.0-rc1
```
