### ISSUE TITLE
Expose chained batch operations queue length

### ISSUE THREAD

**Issue by kemitchell** [Level/levelup#371]
Might y'all welcome a path for exposing the length of batched operation queues in chained batches as part of the public API?

```javascript
var assert = require('assert')
var levelup = require('levelup')
var memdown = require('memdown')

var level = levelup({ db: memdown })
var batch = level.batch().put('a', '1').put('b', '2').del('c')

// New
assert.equal(batch.length, 3)

batch.put('d', '4')

// New
assert.equal(batch.length, 4)
```

In recent adventures I found myself setting a `length` property on batch objects manually, since it was handy to have it ride on the batch during its travels. There's an [internal `ops` array](https://github.com/Level/levelup/blob/662fad8d60f7edc18a5a38631223de3531c0aaa8/lib/batch.js#L17) with a `length`, but I don't see it mentioned in the doc. Mighty tempting.

At the same time, it feels a bit like piling on sugar. I take it `batch([], callback)` is the cake, chained batch is icing, and `length` would be ... sprinkles? Exposing the whole `ops` array seems too much.

I see the fate of batch in general is still open under #270.

Many thanks to all for fine work on levelup and elsewhere!

**Comment by juliangruber** [comment]
we could define .length as a getter, i'm not too worried about old js engines at this point. what do other people think?

**Comment by ralphtheninja** [comment]
I have nothing against this and I definitely see the benefit for having this for testing purposes.

**Comment by juliangruber** [comment]
@kemitchell can you come up with a pull request to add this? that will help speed up the process a lot

**Comment by kemitchell** [comment]
Will do.
