### ISSUE TITLE
Breaking changes after v1?

### ISSUE THREAD

**Issue by JuanCaicedo** [Level/levelup#378]
I'm looking to upgrade from v1.2.0 to 1.4.0 and am just wondering if there are any breaking changes after v1. I checked the changelog, but it looks like it hasn't been updated since then. 

I'm going to try this with my project and I can report back if I have any problems.

**Comment by juliangruber** [comment]
Levelup is following the semver spec, so any breaking changes should be followed by a major version bump. Everything should be good for you.

**Comment by JuanCaicedo** [comment]
Great, thanks!
