### ISSUE TITLE
Best way to throw detect if del() is successful

### ISSUE THREAD

**Issue by julien-f** [Level/levelup#383]
In my API, I throw errors if the user requested to delete something that did not exist, what is the best way to do that with levelup?

I could check for existence first by doing a `get()` but that seems very inefficient, IMHO the best way would be for `del()`'s callback to indicates if it successfully deleted something (like [Redis' `DEL`](http://redis.io/commands/del) which returns the number of deleted keys), but it looks like it is not exposed by levelup :'(

**Comment by jcrugzz** [comment]
@julien-f because `leveldb` is an in process database, the get request should be negligible. I believe thats the only way to do what you are looking for.

**Comment by juliangruber** [comment]
IIUC db.del is just convenience for a single element batch: https://github.com/google/leveldb/blob/master/db/db_impl.cc#L1475

So, probably no, leveldb won't tell us if the value existed. Using locks, you can get and then delete a value safely and performance shouldn't be bad.

**Comment by juliangruber** [comment]
If you're worried about the size of the value, check out this lib: https://github.com/juliangruber/level-exists
