### ISSUE TITLE
Memory leak on batch writes and gets (levelup+leveldown).

### ISSUE THREAD

**Issue by chjj** [Level/levelup#385]
I posted this issue on leveldown, but it may be relevant to levelup as well. I noticed high memory usage with leveldown, but it seems to be significantly worse when using levelup.

Leveldown Issue: https://github.com/Level/leveldown/issues/262

Test case:

``` js
var crypto = require('crypto');
var levelup = require('levelup');
var db = new levelup(process.env.HOME + '/leak.db', {
  keyEncoding: 'ascii',
  valueEncoding: 'binary',
  createIfMissing: true,
  errorIfExists: false,
  compression: true,
  cacheSize: 1 * 1024 * 1024,
  writeBufferSize: 1 * 1024 * 1024,
  db: require('leveldown')
});

var ids = [];
var batch = db.batch();
for (var i = 0; i < 46045; i++) {
  var data = crypto.randomBytes(478);
  var id = 't/t/' + data.slice(0, 32).toString('hex');
  batch.put(id, data);
  ids.push(id);
  id = null;
  data = null;
}

batch.write(function(err) {
  if (err)
    throw err;

  var pending = ids.length;
  ids.forEach(function(id) {
    db.get(id, function(err, data) {
      if (err)
        throw err;
      if (!--pending)
        done();
    });
  });
  ids.length = 0;
  ids = null;

  function done() {
    console.log('done. leaking...');
    setInterval(function() {}, 1000);
  }
});
batch = null;
```

**Comment by jcrugzz** [comment]
@chjj id be interested to see if other backends like [`leveldown-hyper`](https://github.com/level/leveldown-hyper) have the same issue or handle it better. I know from experience it was better at handling a higher write load.

**Comment by chjj** [comment]
@jcrugzz, yeah, I'm considering trying some other backends now that I know that leveldb is pretty cavalier with its allocations. Maybe I'll try rocksdb and lmdb too. Not sure.

Anyway, @rvagg helped me out in the other thread. Closing now.
