### ISSUE TITLE
ZLib compression support?

### ISSUE THREAD

**Issue by mhsjlw** [Level/levelup#387]
A fork of LevelDB https://github.com/Mojang/leveldb-mcpe adds ZLib compression support to replace Snappy as the the default compression. Could support for the ZLib compression be added with an option for people who want to use it?

**Comment by juliangruber** [comment]
do you know why one would favor zlib over snappy? the project's readme doesn't mention it

**Comment by mhsjlw** [comment]
@juliangruber I honestly have no idea, maybe it's better for storing large chunks of binary data? Or maybe in this case they prefer more compression and less speed? I'm only asking for this support because I need to read leveldb databases that have been compressed with ZLib and I'm unable to figure out how this was implemented

**Comment by juliangruber** [comment]
my guess would be to use the aforementioned fork or figure out deflation another way. Who says it would just work with your db if leveldb adds some zlib support?

**Comment by mhsjlw** [comment]
The only reason why I'm asking if there is a way to do it inside of levelup is because i've tried deflating the actual .ldb files inside of the database that are compressed using zlib, that didn't work though. If that's not the right approach, let me know as I may just be able to do this on my own without any modifications to levelup

**Comment by juliangruber** [comment]
it's hard to say without access to the actual db. but unfortunately out of scope for this project to solve. so i'm closing.

feel free to discuss this some more in #leveldb on freenode.

**Comment by clarkx86** [comment]
I know that this topic is already 3 years old, but I would also be interested in this suggestion. Native optional zlib support would be pretty neat to have.

**Comment by vweevers** [comment]
For Mojang db's, see https://github.com/Level/level/issues/119#issuecomment-429183134

**Comment by clarkx86** [comment]
Awesome, thanks **a lot** @vweevers! That got my hopes up again! Unfortunately, I'm running into some more issues. I posted an error log over in the thread you referenced.

**Comment by CtrlAltCuteness** [comment]
I am one of those Minecraft souls who try to fix, or at the very least inspect, what is in my Minecraft save data. Being stuck on two 32-bit ARM Android devices (due to my laptop dying over two years ago) with a small amount of C++ knowledge sadly does not help me learn much about the game. I also dislike having to use the only 3rd-party app that lags every time the keyboard opens, closes, switches which keyboard style it shows, and especially when I expand or collapse parts that it jumps down the scrollable area unexpectedly.
There is a native Android port of `zlib` accessible on Termux as shown when I did an `apt search`:
```
libzopfli/stable 1.0.2-4 arm
  New zlib compatible compressor library

zlib/stable,now 1.2.11-1 arm [installed,automatic]
  Compression library implementing the deflate compression method found in gzip and PKZIP

zlib-static/stable 1.2.11-1 arm
  Static libraries for zlib

zopfli/stable 1.0.2-4 arm
  New zlib compatible compressor tools
```
