### ISSUE TITLE
Is there a levelDOWN for fs?

### ISSUE THREAD

**Issue by fergiemcdowall** [Level/levelup#388]
Sometimes, for whatever reason, compiling levelDB fails. In this case it would be great to be able to use levelup directly on the filesystem.

Is there a levelDOWN available that simply reads/writes to the filesystem?

**Comment by No9** [comment]
Is https://www.npmjs.com/package/level-fsdown this the type of thing you are looking for?

**Comment by fergiemcdowall** [comment]
Yes. Yes it is. :+1:
