### ISSUE TITLE
Create ReadStream with offset

### ISSUE THREAD

**Issue by kevinday** [Level/levelup#392]
Is there an easy way to create a ReadStream with an offset? I'd like to be able to do something like:

`
db.createReadStream({ keys: false, values: true, reverse: true, limit: 5, offset: 10 })
  .on('data', function (data) {
    console.log('value=', data)
  })
`
Would offset be an easy option to add?

**Comment by mcollina** [comment]
What's your use case here? Are you trying to implement pagination?

Given the fact that the db might have changed, you are much better served by using `lt` or `gt` to specify the last element you evaluated

**Comment by juliangruber** [comment]
a naive implementation: https://github.com/juliangruber/offset-stream

**Comment by kevinday** [comment]
@mcollina no, not pagination. I'm trying to replicate an api that supports requests for records starting at the nth element on the first request, so I don't know the n-1th key to compare it with. I'm currently doing something similar to what @juliangruber suggested with offset-stream and it works, but I'd prefer if the stream didn't return the elements at all just to be discarded.

**Comment by vweevers** [comment]
I would suggest designing your keyspace to support this desired feature - which can be implemented entirely in userland on top of the mechanisms offered by `level*`.

For example by prefixing your keys with a sequence number (beware of the sort order, you will need something like [`lexicographic-integer`](https://github.com/substack/lexicographic-integer) to ensure `2` sorts before `10`) and then using range options like `gt` to start reading at a certain offset. You could make the sequence number an incrementing integer or something that's more meaningful to your data, like a timestamp.
