### ISSUE TITLE
uncaught Error: Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by zhangmingze** [Level/levelup#396]
uncaught Error: Could not locate the bindings file. Tried: 
→ C:\Users\mz\Desktop\electron-boilerplate\node_modules\.npminstall\leveldown\1.4.6\leveldown\build\leveldown.node
 → C:\Users\mz\Desktop\electron-boilerplate\node_modules\.npminstall\leveldown\1.4.6\leveldown\build\Debug\leveldown.node
 → C:\Users\mz\Desktop\electron-boilerplate\node_modules\.npminstall\leveldown\1.4.6\leveldown\build\Release\leveldown.node
 → C:\Users\mz\Desktop\electron-boilerplate\node_modules\.npminstall\leveldown\1.4.6\leveldown\out\Debug\leveldown.node
 → C:\Users\mz\Desktop\electron-boilerplate\node_modules\.npminstall\leveldown\1.4.6\leveldown\Debug\leveldown.node
 → C:\Users\mz\Desktop\electron-boilerplate\node_modules\.npminstall\leveldown\1.4.6\leveldown\out\Release\leveldown.node
 → C:\Users\mz\Desktop\electron-boilerplate\node_modules\.npminstall\leveldown\1.4.6\leveldown\Release\leveldown.node
 → C:\Users\mz\Desktop\electron-boilerplate\node_modules\.npminstall\leveldown\1.4.6\leveldown\build\default\leveldown.node

node -v 
v6.3.1
npm -v
3.10.3

and I use ```npm install level --save```

```javascript
var levelup = require('level')
```

chrome dev console message

**Comment by bjackson** [comment]
I have this issue, too. How did you solve it?

**Comment by zhangmingze** [comment]
@bjackson I chose to use sqlite3 instead.
