### ISSUE TITLE
Failed to require LevelDOWN (Path must be a string. Received undefined)

### ISSUE THREAD

**Issue by zhangmingze** [Level/levelup#398]
``` shell
```

**Comment by zhangmingze** [comment]
I cant solve the problem, I am new to electron, please help

**Comment by jcarley** [comment]
`function getLevelDOWN () {
  if (leveldown)
    return leveldown

  var requiredVersion  = require('../package.json').devDependencies.leveldown
    , leveldownVersion

  try {
    leveldownVersion = require('leveldown/package').version
  } catch (e) {
    throw requireError(e)
  }

  if (!require('semver').satisfies(leveldownVersion, requiredVersion)) {
    throw new LevelUPError(
        'Installed version of LevelDOWN ('
      + leveldownVersion
      + ') does not match required version ('
      + requiredVersion
      + ')'
    )
  }

  try {
    return leveldown = require('leveldown')
  } catch (e) {
    throw requireError(e)
  }
}
`

The code above fails on the `var requiredVersion  = require('../package.json').devDependencies.leveldown` when an app is packaged up for production.  More specifically in an electron application that is built with electron-builder, the package.json file for levelup is somehow rewritten to not include the devDependencies section.  So when we run the application, levelup reaches this point, and tries to find the required version number for leveldown, and subsequently blows up.  Not sure what the workaround or fix is for this.
