### ISSUE TITLE
Feature request: .flush()

### ISSUE THREAD

**Issue by fergiemcdowall** [Level/levelup#399]
It would be great if it were possible to `.flush()` (remove all records) a levelUP. Flushing is a fairly common operation for those of us who develop with `levelup` regularly

You can "flush" with the current (`1.3.2`) API by getting all the keys in the db, and then deleting them one by one. However depending on the *-down it is generally a lot faster to delete the store and then reinitialise a fresh store. Therefore it makes sense to extract out `.flush()` into its own API call.

Or does it..?

**Comment by juliangruber** [comment]
With leveldb for example, the cleanest and quickest flush is `rm -Rf db/`. This is highly dependent on the backend, so I'd suggest just having one modules per backend (where required) that implements this functionality.

At least for as long as this doesn't become a highly requested feature, then we might consider adding `.flush()` to the levelup api, but that also has a lot of cost involved towards the whole ecosystem.

**Comment by fergiemcdowall** [comment]
> keep in mind that this has a lot of cost involved towards the whole ecosystem.

Yup- It could be a part of the proposed V2, if that is still on the table https://github.com/Level/levelup/pull/354. Hopefully it would be a _fairly_ painless addition.

**Comment by dominictarr** [comment]
@fergiemcdowall use `require('level').destroy(path, cb)` then reopen the db instance

**Comment by fergiemcdowall** [comment]
@dominictarr is `destroy` available on *-downs other than `leveldown`?

**Comment by dominictarr** [comment]
it's in the leveldown api, https://github.com/level/leveldown#leveldown_destroy
and has test coverage, so it looks like you are in luck!

Although, that doesn't gaurantee a particular implementer has done it though

**Comment by fergiemcdowall** [comment]
OK!

**Comment by fergiemcdowall** [comment]
@dominictarr is there a way to know what kind of *down you have `destroy`ed? Say that you write a program where you allow people to pass in the [storage back end of their choice](https://github.com/level/levelup/wiki/Modules#storage)- how would the program know what kind of backend to reopen? Is it even possible?

**Comment by dominictarr** [comment]
@fergiemcdowall since destroy is a static method, if you are doing it this way, you'd need to pass the constructor + options instead of the initialized database.

**Comment by fergiemcdowall** [comment]
"V2!, V2!"
 \* stands outside building waving placard *

@juliangruber @ralphtheninja

**Comment by ralphtheninja** [comment]
@fergiemcdowall Hehe, soon done. Mostly docs left now.

**Comment by fergiemcdowall** [comment]
Cool- looking forward to trying it out!
