### ISSUE TITLE
Feature request: .getValueAsStream()

### ISSUE THREAD

**Issue by fergiemcdowall** [Level/levelup#400]
I often shoehorn a humungous list into a single levelup `value`, yet only need to read the first few elements when it is `get`-ed. At the moment I have to load the whole value into memory as an Array, before getting the tiny part that I want from the beginning. It would be great if it was possible to store them as strings/blobs, and then stream these large values with something like `.getValueAsStream()`.

Here is somebody else describing this issue, together with a streamy solution for levelDB: http://codeofrob.com/entries/streaming-large-values-from-leveldb.html

Obviously you wouldn't be able to make a "real" value stream for every *-down, that _actually_ reads a stream of bytes without caching the whole thing in memory. But you could definitely do it for a lot of the major stores, and it would be a really powerful feature.

Thoughts?

**Comment by chjj** [comment]
The author of the blog post you mentioned is hesitant about putting large values onto a memory managed heap. Luckily, Buffer objects only take up 80 bytes on the JS heap, regardless of their size.

So, this behavior can be easily layered on top of levelup/down without putting heat on the GC.

1. Store large value list as serialized binary: `[varint-size][value1][varint-size][value2][etc...]`.
2. Get record as a Buffer object. Iterate over and slice out only the values you need. Deserialize them.

I really don't think levelup should be implementing binary serialization formats for the users. 

And this behavior most certainly shouldn't be in leveldown: I'm not sure what the blog post author was getting at there. Copying data _that is already in memory_ from one place to another in small chunks is a new level of pointless -- especially in node.js since we have Buffer objects. It would only _add_ overhead. Maybe C# lacks something similar to node.js Buffers which are stored off the JS heap, but I doubt it. I'm guessing the author just hasn't thought this through well enough.

**Comment by chjj** [comment]
@fergiemcdowall, here's an untested example of what I mean by my explanation above: https://gist.github.com/chjj/bc6b30e228f7af93fe4cbd1528a0b71c

That's the way I would do it (and I more-or-less do it that way in many cases -- it works well).

**Comment by mcollina** [comment]
👎 , I'm with @chjj

**Comment by fergiemcdowall** [comment]
@chjj Thanks for the insight and demo- so levelup `.get()` always returns data as a Buffer object which is inherently _not_ loaded into memory, and can be "streamed" with `readUInt32LE`? If so, then yes, that makes the `.getValueAsStream()` unnecessary.

TIL about node Buffers in levelup 💡 💡 💡

**Comment by chjj** [comment]
@fergiemcdowall, you'll need to pass `{ valueEncoding: 'binary' }` to the options for put and get. The Buffer will be in memory, just not on the JS heap. It's only in memory for C++. Javascript just sees an 80 byte object even if the buffer is 1gb in size. In a sense, Buffers are a way of "tricking" the v8 garbage collector into not bothering with large amounts of data. With the example I posted above, only the string you return from `getItem` will go on the JS heap, the rest of the data never even enters JS-land.

**Comment by fergiemcdowall** [comment]
OK- so Buffers load their payload into memory, but not the memory used by the node process.

**Comment by juliangruber** [comment]
level-store solves exactly that in user-space: https://github.com/juliangruber/level-store

```js
var level = require('level');
var Store = require('level-store');
var fs = require('fs');

var store = Store(level('/tmp/level-store'));

fs.createReadStream(__dirname + '/file.txt')
  .pipe(store.createWriteStream('file'))
  .on('close', function () {
    // file.txt is stored in leveldb now
    store.createReadStream('file').pipe(process.stdout);
  });
```

It achieves this by putting each stream chunk into its own key/value pair.

**Comment by fergiemcdowall** [comment]
@juliangruber interesting, I have already gone some way down that road- is level-store fairly stable?

**Comment by chjj** [comment]
@fergiemcdowall, there are 2 heaps within node.js:

- Native Heap (manual memory management): C++, std::string, leveldb::Slice, Buffer.
- Javascript/VM Heap (garbage collector): String, Object, Array, Number, RegExp, etc.

The blog post author is concerned that putting too much data on the VM heap will cause the garbage collector's head to explode (it can). But you'll notice above that all javascript objects (String/Object/etc) live inside the VM heap, with one notable exception: Buffer objects. Their data still resides in the native heap, so it doesn't confuse the garbage collector. Buffer objects already solve what the author of that post was trying to solve.

When levelup gets json for you, the flow looks like: `std::string->String->JSON.parse->Object`.

When levelup gets a buffer for you, the flow looks like: `std::string->Buffer`.

In the first case, as soon as std::string gets converted into a javascript String, it enters the VM heap and all of it's data is now managed by the garbage collector, putting potential stress on the GC.

However, when std::string gets converted into a Buffer object in the second case, the buffer's data never enters into the VM heap (which we're worried about putting too much data on). It still lives within the native heap, so there's no danger of pulling to much stuff out of the database.

**Comment by fergiemcdowall** [comment]
@chjj OK- that sounds sensible, and I guess its reasonable to assume that `std::string->Buffer` is faster than `std::string->String->JSON.parse->Object` ?

**Comment by chjj** [comment]
@fergiemcdowall yes, but it's not just that it's faster, the benefit comes from the fact that the javascript engine doesn't stress itself out trying to manage a huge piece of data.

If you have a JSON array like:

```
[
  { object1: 'foo' },
  { object2: 'foo' },
  <10,000 more objects here>
  { object10000: 'foo' }
]
```

It would be better to store it in a Buffer, and only parse the single object you need out of that list of objects like I showed above. That way, you don't have 10,000 objects going on the JS heap when it's not necessary.

**Comment by fergiemcdowall** [comment]
@chjj Suddenly I have lots to do!

**Comment by chjj** [comment]
@fergiemcdowall, that's the best time to write code. :)

Just make sure you're thinking about you're data management in the right way. If you have tons of values stored under one key in the database and you only need 1 or 2 of them, it might be better to put each value under its own key if possible.

**Comment by chjj** [comment]
Closing.
