### ISSUE TITLE
Error in using LevelDB in Azure node.js App service

### ISSUE THREAD

**Issue by newdev7** [Level/levelup#401]
I'm trying to create a Node.js app with this library in Microsoft Azure app service. I followed the steps given in this [link](https://azure.microsoft.com/en-us/documentation/articles/app-service-web-nodejs-get-started/) to create an app. I ran that locally (Windows10 64bit) and pushed it to the Azure. When I open the site in browser, it returns HTTP 500 error.

When I run `npm start` in the terminal on `https://{app-name}.scm.azurewebsites.net/DebugConsole` , it returns the error at.

```
    at D:\home\site\wwwroot\node_modules\levelup\lib\levelup.js:119:34
    at D:\home\site\wwwroot\node_modules\abstract-leveldown\abstract-leveldown.js:39:16
Express server listening on port 3000    

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\4.4.7\\node.exe" "D:\\Program Files (x86)\\npm\\2.15.8\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! appName@0.0.1 start: `node app.js`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the appName@0.0.1 start script 'node app.js'.
npm ERR! This is most likely a problem with the appName package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appName
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls appName
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\home\site\wwwroot\npm-debug.log
```

I checked the code in `levelup.js:119:34` and added the log for that error. That log returns `The filename, directory name, or volume label syntax is incorrect.`

I'm using this library for storing the data. I initialised the db by `var db = levelup('./mydb', { valueEncoding: 'json'});`

What should I do to use the levelDB in Microsoft Azure? Any help would be appreciated. Thanks.

**Comment by ralphtheninja** [comment]
@newdev7 This might be due to windows not liking `'./mydb'`. Try something else, like `'mydb'`.

**Comment by juliangruber** [comment]
so it works locally on windows, but not on azure?

**Comment by juliangruber** [comment]
see also https://coderead.wordpress.com/2013/08/27/running-leveldb-in-windows-azure-websites/, which seems to suggest a similar fix

**Comment by juliangruber** [comment]
try `level(path.join(__dirname, 'db'))`

**Comment by newdev7** [comment]
@ralphtheninja @juliangruber Tested with different paths. Instead of `./mydb`, tried `mydb` and `level(path.join(__dirname, 'db'))`. Also tried to initialize the db like this `var db = require('level')('mydb');`. But still got the same error.

**Comment by juliangruber** [comment]
hmm, does anyone feel like jumping into azure and debugging this?

**Comment by vweevers** [comment]
The Windows kernel has always supported forward slashes, even back in DOS. The problem only arises in command lines, where "/" is often parsed as a switch delimiter. Doesn't apply in this case.

I tried to deploy a test site just now, and found that compiling native modules on Azure is a pain. Though this could be because of my free account:

> For a reason that is not fully understood yet, a subset of modules [..] fail to install on free/shared Web Apps, but install fine on dedicated Web Apps (i.e. basic/standard).
> https://github.com/projectkudu/kudu/issues/1076#issuecomment-156845856

When I installed the latest leveldown (1.5.0) - which has prebuilds, 1.4.6 does not - the following example runs without problems:

```js
const levelup = require('levelup')
const db = levelup('./db')

require('http').createServer((req, res) => {
  db.put('hello', 'world', (err) => {
    if (err) throw err
    res.end('hello world')
  })
}).listen(process.env.port || 3000)
```

@newdev7 did you see any errors in the deployment output (`git push azure master`)?

**Comment by ralphtheninja** [comment]
@newdev7 Is this still a problem? Please re-open if that's the case.
