### ISSUE TITLE
memdown never tricker?

### ISSUE THREAD

**Issue by katopz** [Level/levelup#402]
When I try...
```js
  levelup({ db: memdown }, function (err, db) {
    console.log(err, db);
  })
```
or
```js
  levelup(memdown, function (err, db) {
    console.log(err, db);
  })
```
`callback` will never fire because `options` always get override internally.
- - -
BTW, this one work with empty  `options` 
```js
  levelup(memdown, {}, function (err, db) {
    console.log(err, db);
  })
```
Is this expected behavior? is not quit same as `README` said...
How can I properly get callback with `memdown`?

Thanks

**Comment by ralphtheninja** [comment]
You're missing the `location` parameter. The following will run your callback:

```js
const levelup = require('levelup')                       
levelup('foo', { db: require('memdown') }, (err, db) => {
  console.log(err, db)                                   
})                                                       
```

**Comment by ralphtheninja** [comment]
Also see the [memdown docs](https://github.com/Level/memdown#example)

**Comment by juliangruber** [comment]
This part is kinda tricky, yeah, but that's why we created a bunch of convenience packages, like

- level
- level-mem
- memdb

**Comment by katopz** [comment]
@ralphtheninja here's doc said

> The levelup(db, callback) form (with optional callback) is only available where db is a factory function, as would be provided as a 'db' property on an options object (see below). Only for back-ends that **don't require a location argument, such as MemDOWN**.

So I think it didn't required **location** argument. and docs didn't provide any working examples for `memdown` + callback anywhere tho.

Thanks anyway.
