### ISSUE TITLE
createReadStream did not execute end callback

### ISSUE THREAD

**Issue by milu2003** [Level/levelup#404]
i use it in electron.

and i create leveldb in main like this:

```
 let testdb = levelup('testc.db', {});
 global.testdb = testdb;

```

use it in renderer:
```
let testdb = remote.getGlobal('testdb');
testdb.createReadStream(this.valueOps)
		.on('data', function (data) {
		    console.log(data.key, '=', data.value)
		 })
		 .on('end', function () {
			 console.log('finsh')//don't not run here
		 })

```

don't not run end, why?

**Comment by milu2003** [comment]
The problem is solved.

Add this before each load：
```
this.db.close();
this.db.open();
```

**Comment by juliangruber** [comment]
maybe that's an electron related issue, try creating the db in the renderer process

**Comment by milu2003** [comment]
@juliangruber i try it.

Every process renderer use, the database will be locked up
If you want to use, you must delete the lock file and re create it.

When more than one renderer process are used, the data can cause errors, and the data can be damaged.

**Comment by juliangruber** [comment]
ok I see. Can you please create a minimal runnable example that demonstrates this?

**Comment by milu2003** [comment]
@juliangruber  ok,thanks for your help。

now I have a new idea, if not every process renderer is create a new db, but to share one
Will be able to solve this problem? But it feels like a lot of trouble.

**Comment by milu2003** [comment]
@juliangruber  hello,i create a example at:https://github.com/milu2003/electron-leveldb-demo

**Comment by juliangruber** [comment]
i would strongly suggest you to use a push state routing strategy instead of literally reloading html pages with a shared global leveldb instance

**Comment by milu2003** [comment]
@juliangruber What is it, can you say it in detail?

**Comment by milu2003** [comment]
@juliangruber  I'm using your project： multilevel

The problem is solved, but a lot of data reading and writing, performance is still a little loss, a large amount of data, the performance is worse than 20 times
