### ISSUE TITLE
Document the difference between the `close` and `end` events

### ISSUE THREAD

**Issue by justanotheranonymoususer** [Level/levelup#405]
Document the difference between the `close` and `end` events.
Currently, the difference is not clear. Even the example log string is the same:

```
  .on('close', function () {
    console.log('Stream closed')
  })
  .on('end', function () {
    console.log('Stream closed')
  })
```

**Comment by juliangruber** [comment]
Good observation, I changed the second log to `Stream ended`.

The `"close"` and `"end"` events are part of nodejs, see https://nodejs.org/api/stream.html#stream_event_close_1 and https://nodejs.org/api/stream.html#stream_event_end, therefore we shouldn't need to document them in this project.
