### ISSUE TITLE
is it safe to put data during reading from createReadStream?

### ISSUE THREAD

**Issue by skygragon** [Level/levelup#407]
e.g. add new key, delete existing key, or update the same key... Will it invalidate any "cursor/iterator" internally?

**Comment by ralphtheninja** [comment]
Afaik it should be fine if you're using leveldown as backend, since createReadStream() means a new iterator which means a snapshot. This might not be the case with another backend, e.g. memdown. Someone please correct me if I'm wrong.

**Comment by vweevers** [comment]
It's safe in memdown too, thanks to [functional-red-black-tree](https://www.npmjs.com/package/functional-red-black-tree).

**Comment by skygragon** [comment]
Yep, I'm using leveldown. Does it mean that after I createReadStream(), any new modifications will not be emitted on that stream, and I only see those "old" values in snapshot? So to get those changes I have to create a new stream?

**Comment by vweevers** [comment]
That's correct.

**Comment by skygragon** [comment]
Thanks dude!
