### ISSUE TITLE
Is accessing LevelDOWN from LevelUP possible? Could/should it be?

### ISSUE THREAD

**Issue by metabench** [Level/levelup#410]
The LevelUP API has been convenient so far in a database server I am making. Partly in the interests of performance, and partly for the flexibility provided by iterators, I am interested in using LevelDOWN. To be able to incrementally improve my codebase, I would like to access LevelDOWN from LevelUP.

Is that supported with the current API? Would it be worth supporting?

**Comment by juliangruber** [comment]
You can access the leveldown instance through `.db`, like eg

```js
var db = levelup('./my-db')
var leveldown = db.db
```

**Comment by metabench** [comment]
@juliangruber Thanks. It's nice that it's that simple. It's definitely worth mentioning this in the 'Relationship to LevelDOWN' part of the docs.
