### ISSUE TITLE
leveldb in a queue

### ISSUE THREAD

**Issue by superhero** [Level/levelup#411]
I see a few discussion threads here, so I shoot a question as well..

Is it possible, or better yet, is it the right tool, to use leveldb when designing a FIFO component? As I can tell, it's a key based persistence. Is it also possible to work with leveldb as a stack or list?

**Comment by fergiemcdowall** [comment]
You sort of kind of could- it depends how much you are prepared to munge keys.

If you prepend all keys with a fixed-length (padded) timestamp on the way in, then they will exist in the index in order of insertion. You can then read off documents sorted by time of insertion from any point in the index, in ascending or descending order

**Comment by superhero** [comment]
@fergiemcdowall yes, I understood it's possible to do it in this way. However, I was concerned about the performance for FIFO and LIFO operations as the tool seems to address a completely different problem, eg: key matching. I love that part of the tool ofc, why I'm interested in using the same tool as I use for key based operations in different part of the code for these list operations. The list can be millions of keys and they all come in in batches, and all I really need is the beginning and end part of the list. I started working on a c++ code to solve it my self, but figured that maybe leveldb has a way to do this. The more I read I do however understand that these operations is not what level db was created for, but would probably fit my needs sense I can manipulate it in the way you described for instance.
