### ISSUE TITLE
pipe method not described in readme

### ISSUE THREAD

**Issue by jakehm** [Level/levelup#414]
> The standard pause(), resume() and destroy() methods are implemented on the ReadStream, as is pipe() (see below). 'data', 'error', 'end' and 'close' events are emitted.

but I can't find it.

**Comment by zy445566** [comment]
easy,just like these:
db.createReadStream()
db.createKeyStream()
db.createValueStream()
for example:
var levelup = require('levelup');
levelup('temp',(err,db){
     db.on('put',(key, value)=>{
	console.log(key+'='+value)
     });
   db.put('test1','test1');
  db.put('test2','test2');
  db.put('test3','test3');
})

**Comment by jakehm** [comment]
But your example doesn't use a pipe() method.

**Comment by ralphtheninja** [comment]
The pipe method is part of `ReadableStream` which is linked to in the README. That said I think the `(see below)` part is confusing since there isn't anything below related to that sentence.
