### ISSUE TITLE
move to standard

### ISSUE THREAD

**Issue by juliangruber** [Level/levelup#416]
Shall we do this? Easier contribution and no worries about style changes.

**Comment by diasdavid** [comment]
yes please! :)

**Comment by ralphtheninja** [comment]
@juliangruber At time of writing you have 8 thumbs up and 2 hearts and no negative reaction. *nudge*nudge*

**Comment by juliangruber** [comment]
i'm too lazy rn, does anyone else wanna do this? :P

**Comment by ralphtheninja** [comment]
I can have a look

**Comment by ralphtheninja** [comment]
@juliangruber What about the other branches, e.g. `encoding-down`, `remove-encodings` etc? Should I just go ahead and convert `master` and worry about the other branches later?

**Comment by juliangruber** [comment]
i think so, yes. we can move them later
