### ISSUE TITLE
Error when push into Array

### ISSUE THREAD

**Issue by EasonWang01** [Level/levelup#421]
Is leveldb unable to save Array type?Because it will convert it to string.

<img width="949" alt="2017-03-03 9 57 23" src="https://cloud.githubusercontent.com/assets/11001914/23535192/e7e01a74-fff7-11e6-86f5-e234f3a27912.png">

<img width="1009" alt="2017-03-03 10 03 48" src="https://cloud.githubusercontent.com/assets/11001914/23535334/bc8b96b8-fff8-11e6-849d-abe9b0232a7c.png">

**Comment by ralphtheninja** [comment]
What is the error here? It seems to work as expected.

**Comment by ralphtheninja** [comment]
You do:

```js
db.put('All_Nodes. JSON.stringify([ NodeInfo ]), cb)
```

which means you will store the stringified version of the array, so it's you doing the conversion to string, not leveldb.

**Comment by EasonWang01** [comment]
but if I parse it then it't back to  an array then push,but the length is the same.

**Comment by ralphtheninja** [comment]
You're pushing something to a temporary array. This is how javascript work :)

**Comment by EasonWang01** [comment]
no,the behavior is not like browser,what I want to do is push something into value,but not works

**Comment by ralphtheninja** [comment]
```
> var stringified = JSON.stringify([ 'a', 'b' ])
undefined
> stringified
'["a","b"]'
> console.log(JSON.parse(stringified).push('c'))
3
undefined
> stringified
'["a","b"]'
```

**Comment by ralphtheninja** [comment]
It doesn't work because your code has a bug. It's not related to leveldb at all.

**Comment by ralphtheninja** [comment]
To be more clear, the last line should be

```
> JSON.parse(stringified)
[ 'a', 'b' ]
```

**Comment by EasonWang01** [comment]
ok,I got it,should not write push after parse
 should be

```
        var v = JSON.parse(value)
        v.push({a:12});
        console.log(v);
```

thanks
