### ISSUE TITLE
package.json Metadata in Browser Bundles

### ISSUE THREAD

**Issue by kemitchell** [Level/levelup#423]
I noticed that browser bundles with `levelup` include a bunch of `package.json` metadata, including the content of `README`.  Best I can tell, `package.json` ends up in the `require` graph from `lib/util.js`, which loads both `levelup`'s and `leveldown`'s `package.json` files for a compatibility check.  When installing `levelup` with `npm`, the CLI pulls `package.json` down from the registry.  Registry package metadata objects inline lots of additional data, like `README` content.

Would y'all welcome a patch that adds `prepublish` and `pretest` scripts to extract versions from `levelup` and `leveldown` `package.json` into standalone files, and has `lib/util.js` require those files, instead?

**Comment by juliangruber** [comment]
SGTM!
