### ISSUE TITLE
Question: Is db files cross platform capable?

### ISSUE THREAD

**Issue by superhero** [Level/levelup#425]
As the title says; **is db files cross platform capable?**

I tried between two different systems, but very similar, with no issue. Just wondering if there's any restriction that I don't see from my very narrow test?

**Comment by juliangruber** [comment]
are you talking about taking the files of a db created in one os and then loading them in another? afaik this is supported

**Comment by superhero** [comment]
yhea, different OS, different CPU architecture, filesystem etc...
...great, in that case I don't need to do some sort of backup in a different format.
