### ISSUE TITLE
getLevelDown is not a function.

### ISSUE THREAD

**Issue by diasdavid** [Level/levelup#426]
With 1.3.6 release, I've started getting errors of `getLevelDown is not a function` coming from a browserified version of this module and I've narrowed down the problem to the usage at:

- https://github.com/Level/levelup/blob/master/lib/levelup.js#L114
- https://github.com/Level/levelup/blob/master/lib/levelup.js#L385

The function should only be called if it actually exists, i.e `getLevelDOWN && getLevelDOWN()` or sorts. Would you take a PR with this? This change is giving me a hard time to circumvent since it was released as a patch version.

It would also be great if this module got its tests running on the browser.

**Comment by ralphtheninja** [comment]
Oh right. So apparently browserifying the code does _not_ make requiring `lib/leveldown.js` something falsey but instead an empty object. cc @juliangruber

**Comment by diasdavid** [comment]
All good now. Thank you so much for responding so quickly! ❤️
