### ISSUE TITLE
add node 8 to travis

### ISSUE THREAD

**Issue by ralphtheninja** [Level/levelup#431]
and remove 0.12?

**Comment by mcollina** [comment]
I think for removing 0.12 we should bump the major, shouldn't we?

**Comment by dcousens** [comment]
@mcollina not if its just from travis.

**Comment by mcollina** [comment]
how can we assure this library would still works on node 0.12 if it is not on travis?

**Comment by dcousens** [comment]
@mcollina we don't assure that - as `0.12` is out of LTS.  Not even Node assures `0.12` works anymore.

**Comment by juliangruber** [comment]
yes, but our promise was to support node 0.12, not "any node that has LTS"

**Comment by dcousens** [comment]
Then major bump :+1:
