### ISSUE TITLE
[question] What is the recommended way to pipe a stream of objects into a db?

### ISSUE THREAD

**Issue by fergiemcdowall** [Level/levelup#433]
Say you are downloading a stream of key-value objects from a file or url- what would be the most elegant way to pipe them into a db?

**Comment by ralphtheninja** [comment]
Check out this section in the readme https://github.com/Level/levelup#what-happened-to-dbcreatewritestream

**Comment by ralphtheninja** [comment]
For example using `pgte/level-writestream`

```js
var ws = db.createWriteStream();
ws.write({key: 'A', value: 'B'}, function(err) {
  if (err) throw err;
});

source.pipe(ws);

ws.once('finish', function() {
  console.log('finished');
});
```

**Comment by fergiemcdowall** [comment]
For a regular yet casual user such as myself- its a bit tricky to gauge which writestream lib is the "best" (for whichever values "best" you have that day). It would be great to see some kind of pipeability back in the core, even if it had performance tradeoffs.

**Comment by fergiemcdowall** [comment]
But thanks for the answer :)
