### ISSUE TITLE
Initializing levelup changes the data store

### ISSUE THREAD

**Issue by tueric** [Level/levelup#434]
Not exactly sure if this is a bug, but when I have an existing leveldb store, and I initialise the levelup instance, it will change the files itself. Specifically my program is modifying my leveldb store here `var blockchainDB = level('<PATH TO LEVELDB>' );`.

**Comment by ralphtheninja** [comment]
@tueric What do you mean 'it will change the files itself'? Do you mean that the data has changed, as in deleted etc?

**Comment by tueric** [comment]
The .ldb files will change names, usually some of them will increment by 1. I've also seen the size of the database folder change as well.

**Comment by ralphtheninja** [comment]
Might be because of compaction etc.

**Comment by tueric** [comment]
@ralphtheninja shall i reopen the issue in the leveldown repo? Is this a thing that can be disabled in the first place (compaction, etc)?

**Comment by fergiemcdowall** [comment]
@tueric leveldb storage files are essentially volatile- I am pretty sure this is by design
