### ISSUE TITLE
promise layer

### ISSUE THREAD

**Issue by juliangruber** [Level/levelup#439]

**Comment by mcollina** [comment]
I would say we should limit this to native promises, i.e. no bluebird. This would imply we move our minimum version of Node.js to 4 (We should do that anyway)

**Comment by juliangruber** [comment]
+1

**Comment by pfrazee** [comment]
I cannot await for this

**Comment by juliangruber** [comment]
WIP pull request here: https://github.com/Level/levelup/pull/455

**Comment by ralphtheninja** [comment]
Done!
