### ISSUE TITLE
deprecate backend specific options

### ISSUE THREAD

**Issue by juliangruber** [Level/levelup#440]
- [x] errorIfExists
- [x] createIfMissing
- [x] compression
- [x] cacheSize

**Comment by ralphtheninja** [comment]
`deprecate` -> `remove`?

**Comment by juliangruber** [comment]
we haven't deprecated them yet. I was thinking you _should_ always deprecate first, but I'm also ok with just removing them, since this is a bigger change already.

**Comment by ralphtheninja** [comment]
How can you deprecate properties? Just curious how you would do it.

**Comment by juliangruber** [comment]
use the deprecate function on a getter i guess

**Comment by ralphtheninja** [comment]
> but I'm also ok with just removing them, since this is a bigger change already.

I'll make sure to write an upgrade guide that summarizes what has been changed

**Comment by ralphtheninja** [comment]
@juliangruber Oh, we should probably remove `.compression` and `.cacheSize` as well, right?

**Comment by juliangruber** [comment]
absolutely!

**Comment by maxlath** [comment]
sorry for digging up a (relatively) old issue, but what was the motivation for removing those options?
(For context on my side: I was considering increasing the `cacheSize` of a db, before reading here that this option had been removed)

**Comment by vweevers** [comment]
These options don't belong in `levelup`, because it is backend agnostic. Most of these options are leveldown-specific, and cannot be supported by other stores (aka backends).

**Comment by maxlath** [comment]
@vweevers thanks. So I would need to do something like this?
```js
const level = require('level')
const db = level('./db')
db.db.open({ cacheSize: 512 * 1024 * 1024 }, cb)
```
I don't see any other way to pass the option, but isn't it an issue to re-open the database? (sorry for the possibly noobish question)

**Comment by vweevers** [comment]
These options are still supported, level(up) just doesn't know anything about them. You can do:

```js
const level = require('level')
const db = level('./db', { cacheSize: 512 * 1024 * 1024 })
```

And level will pass those options to leveldown on open.
