### ISSUE TITLE
Promisifying Level, issue with encodeLtgt?

### ISSUE THREAD

**Issue by eslachance** [Level/levelup#454]
Hey guys,

Not sure if this really is the proper place to ask, but I'll try anyway (unless you guys have a Discord or Slack server). 

I'm attempting to promisify `level` in my own way - the existing `then-level` isn't actually working, a few issues pushed me to work on my own version, which also happens to support node 8 native promisifying using the `util` module.

The full code is gisted [here](https://gist.github.com/eslachance/fffe3001149c0783a6a227db273e0341). The issue I have specifically is when attempting to create a `createKeyStream`.

Code:
```js
const lp = new LevelPromise('hallo');

const test = async() => {
  await lp.put('hallo', 'hehe');
  const rv = await lp.get('hallo');
  console.log(rv);
  
  const output = [];
  lp.createKeyStream()
    .on("data", key => lp.get(key).then(d => output.push(JSON.parse(d))))
    .on("end", () => console.log(output));
  
  //await lp.close();
  //lp.destroy();
}

test();
```

Resulting Error:

```
Uncaught Promise Error:  TypeError: Cannot read property 'encodeLtgt' of undefined
    at LevelPromise.LevelUP.readStream.LevelUP.createReadStream (/root/level-promise/node_modules/levelup/lib/levelup.js:323:24)
    at LevelPromise.LevelUP.keyStream.LevelUP.createKeyStream (/root/level-promise/node_modules/levelup/lib/levelup.js:336:15)
    at test (/root/level-promise/index.js:61:6)
    at <anonymous>
```

I'm not having this issue without the promisify stuff, createKeyStream works correctly.

**Comment by ralphtheninja** [comment]
So it seems that `this._codec` is undefined. I think it might be related to this line https://gist.github.com/eslachance/fffe3001149c0783a6a227db273e0341#file-level-promise-js-L16 , since you're not binding `.createKeyStream()` to anything?

**Comment by ralphtheninja** [comment]
You could try with `.createValueStream()` and I bet you get the same error.

**Comment by vweevers** [comment]
> since you're not binding .createKeyStream() to anything

Yup, that's it. It's somewhat a mixup of patterns. This is decoration:

```js
this[key] = promisify(prototype[key]).bind(this.level);
```

But this is inheritance:

```js
this[key] = prototype[key];
```

I would also recommend less magic (of detecting methods with a callback). Being explicit communicates which methods you're promisyfing:

```js
class LevelPromise {
  constructor(location) {
    this.level = level(location);

    this.get = promifisy(this.level.get.bind(this.level));
    this.put = promifisy(this.level.put.bind(this.level)); // etc
  }

  createKeyStream(...args) {
    return this.level.createKeyStream(...args);
  }

  createValueStream(...args) {
    return this.level.createValueStream(...args);
  }

  // etc
}
```

Hope that helps :)

**Comment by eslachance** [comment]
I was actually definitely binding `keyStream` automatically in https://gist.github.com/eslachance/fffe3001149c0783a6a227db273e0341#file-level-promise-js-L16 . However, vmweevers put me on the right track: `this[key] = prototype[key];` doesn't work for... honestly I'm not exactly sure, the exact inner workings of javascript are sometimes a little beyond me. 

The whole point of abstracting the methods without specifically pointing them out one by one is to make myself at least semi-pseudo-almost-temporarily future-proof, so I at least don't have to push out a new version every time an alias changes or a method is added/removed. As long as the structure remains, it'll be fine. 

So I'm stubborn and went ahead with this: 
```js
    Object.keys(prototype).forEach(key => {
      if(this._hasParam(prototype[key], "callback")) {

        this[key] = promisify(prototype[key]).bind(this.level);
      } else {
        this[key] = (...args) => this.level[key](...args);
      }
    });
```

And it does work fine at the moment. Certainly better than `then-levelup` that simple **didn't** manually bind half the things I need...

So my initial release: [native-level-promise](https://www.npmjs.com/package/native-level-promise) , still lacking docs, and more extensive testing!

**Comment by ralphtheninja** [comment]
```js
this[key] = (...args) => this.level[key](...args);
```

_Now_ you're binding ;) This should be the same as doing

```js
this[key] = this.level[key].bind(this.level);
```

**Comment by vweevers** [comment]
> However, vmweevers put me on the right track: this[key] = prototype[key]; doesn't work for... honestly I'm not exactly sure, the exact inner workings of javascript are sometimes a little beyond me.

Credit goes to @ralphtheninja 💘 

@eslachance The reason that `this[key] = prototype[key]` doesn't work is because in JavaScript the [value of `this` is determined by how a function is called]( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this).
