### ISSUE TITLE
Update typescript definitions

### ISSUE THREAD

**Issue by MeirionHughes** [Level/levelup#467]
* [current definitions ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f3b9cb6f5173c36695c4d3cb39a950c6448ddaf2/types/levelup/index.d.ts) out-of-date for `2.0` - and for 1.x too in places. 

I can pr to defiantly-typed if you'd prefer to keep it there. Alternatively, if you'd like, I could PR into here and make the type definitions a first-class citizen of the package. I'd be happy to maintain.

**Comment by ralphtheninja** [comment]
I don't have an opinion on where to put the definitions.

@MeirionHughes What would the difference be for people using typescript?

I'm all for helping out typescript users and reducing friction!

**Comment by MeirionHughes** [comment]
Its not that big an improvement. It just means ts users don't have to have to also install `@types/levelup` - not an issue really. 
 
The main difference is that as being part of the repo it is more likely the definitions can be kept more up to date with lib changes.

**Comment by vweevers** [comment]
Including it here would also make the definitions versioned, right? Sounds like a good thing

**Comment by ralphtheninja** [comment]
@MeirionHughes Lets make it happen. Want to be part of `level` org?

**Comment by MeirionHughes** [comment]
Sure, can do! :) I'd also like to look at getting es6 `Symbol.iterator` into here too - it would be a natural fit for the underlaying c++ iterator.

**Comment by ralphtheninja** [comment]
@MeirionHughes Invited! Welcome :)

**Comment by liukun** [comment]
Great! Looking forward to this!

**Comment by MeirionHughes** [comment]
Anyone using typescript: https://github.com/Level/levelup/pull/475 could do with a review and potentially a manual test.

**Comment by MeirionHughes** [comment]
@ralphtheninja I'm still working on this. Currently, the types will work, but anyone wanting to implement the `level.AbstractDOWN` interface will need to import it from `levelup`. 

So it needs to be moved out somewhere --otherwise leveldown will be importing from levelup-- ideally to something like `level-types` to hold the "base" types.

**Comment by MeirionHughes** [comment]
here is an example of what I'm talking about: 

![image](https://user-images.githubusercontent.com/3584509/30272923-ac2202c0-96ee-11e7-8966-9d91b5d1b239.png)

@ralphtheninja so, am I okay to create repo: `level/abstract-types`?

**Comment by vweevers** [comment]
Can't we add those type definitions to https://github.com/Level/abstract-leveldown?

**Comment by MeirionHughes** [comment]
yes, you could; so long as you're happy with things like `leveldown` and `encoding-down` having a dev dependency to `abstract-leveldown`?

**Comment by vweevers** [comment]
Those directly depend on (and extend) `abstract-leveldown` :)

**Comment by MeirionHughes** [comment]
ah ok; I thought `leveldown` was doing its own thing with gyp. problem solved. 💃
