### ISSUE TITLE
Strategy for supporting node versions

### ISSUE THREAD

**Issue by ralphtheninja** [Level/levelup#470]
I was going through the LTS schedule for node. And at time of writing it looks like:

![image](https://user-images.githubusercontent.com/308049/30002324-afbdb88c-90a6-11e7-93c9-590d57218a6c.png)

Currently I'm a bit confused on what strategy we should pick. Updating `.travis.yml` etc feels a bit random to me atm. Therefore I'd like us to have a clear strategy on which versions we should support and test on.

Here are some alternatives:

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BS3PGFJJJDTHN3DN19N7QF39/support%20active%20versions%3A%204%2C%205%2C%206%2C%207%2C%208)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BS3PGFJJJDTHN3DN19N7QF39/support%20active%20versions%3A%204%2C%205%2C%206%2C%207%2C%208/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BS3PGFJJJDTHN3DN19N7QF39/support%20active%20lts%20versions%3A%204%2C%206%2C%208)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BS3PGFJJJDTHN3DN19N7QF39/support%20active%20lts%20versions%3A%204%2C%206%2C%208/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BS3PGFJJJDTHN3DN19N7QF39/support%20active%20versions%20with%20enough%20es6%20features%3A%206%2C%207%2C%208)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BS3PGFJJJDTHN3DN19N7QF39/support%20active%20versions%20with%20enough%20es6%20features%3A%206%2C%207%2C%208/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BS3PGFJJJDTHN3DN19N7QF39/support%20active%20lts%20versions%20with%20enough%20es6%20features%3A%206%2C%208)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BS3PGFJJJDTHN3DN19N7QF39/support%20active%20lts%20versions%20with%20enough%20es6%20features%3A%206%2C%208/vote)

With "enough es6 features" I mean at least have support for destructuring (since we currently started using this for `levelup@2.0.0`)

cc @Level/owners

**Comment by ralphtheninja** [comment]
I personally picked the second options, i.e. all active even numbers. It's a simple rule and the odd numbering is a bit confusing to me.

**Comment by vweevers** [comment]
My bad, when I said elsewhere that node 5 hasn't reached end of life. I guess I was also confused about the odd numbers. With that short a lifetime, supporting them isn't worth the while.

@ralphtheninja seeing as you listed 4 under "active lts versions" do you mean to also include maintenance mode?

I do like what we (I) added to the `leveldown` readme (though it's a different situation from `levelup`, due to the prebuilds):

> We aim to support *at least* Active LTS and Current Node.js releases.

We could improve the wording of that statement; what I meant with "at least" is this. *Versions (like 5 and 7) near officially supported numbers (6 and 8) usually do work but we offer no guarantees. Prebuilds are provided as a courtesy, until they cause us problems, then we may decide to drop them without notice.*

**Comment by mcollina** [comment]
IMHO we should support current + active LTS versions. This would mean that active LTS releases are supported for 2 years.

I think that removing a supported version should be a semver-major change. This would mean that if we bump again in one year, we can drop support for node 6 and 9.

**Comment by ralphtheninja** [comment]
> @ralphtheninja seeing as you listed 4 under "active lts versions" do you mean to also include maintenance mode?

Aye. I was a bit unclear. I meant _supported_ versions.

**Comment by ralphtheninja** [comment]
@mcollina Does this mean that we right now would support 6 and 8? And once 8 goes into active LTS (October 2017), we add 9 as current? (I assume by active LTS you mean the blue bar and not the maintenance phase)

**Comment by ralphtheninja** [comment]
Hehe, I still think this is super confusing, maybe it's just me. I want to find the simplest explanation. How about this. If you take a look at the time line above and imagine a vertical line going down from the timeline, this would mean all version that _intersect_ either a blue or green bar.

**Comment by ralphtheninja** [comment]
@mcollina After sleeping on it, it makes sense what you suggest. And by the same logic we should remove node 7 from travis now, since it's no longer active, with node 6 and 8 left and starting to support node 9 1st of October.

**Comment by vweevers** [comment]
So it'll be the same policy as leveldown's, except in leveldown, we do provide prebuilds for "inactive" versions as a courtesy? Because if we follow the same reasoning here, we could keep node 7 in levelup, as a courtesy, simply until the build fails one day.

**Comment by mcollina** [comment]
@ralphtheninja exactly. V2 would support 6, 8, 9 and 10, then V3 will be 8, 10, 11 and 12. And so on.

**Comment by vweevers** [comment]
Anyone know of more up-to-date usage stats than https://twitter.com/seldo/status/712386414902521861?

**Comment by ralphtheninja** [comment]
> So it'll be the same policy as leveldown's, except in leveldown, we do provide prebuilds for "inactive" versions as a courtesy? Because if we follow the same reasoning here, we could keep node 7 in levelup, as a courtesy, simply until the build fails one day.

`leveldown` is a bit different since it's a native add-on so it makes more sense to not be as strict there



> Anyone know of more up-to-date usage stats than https://twitter.com/seldo/status/712386414902521861?

I'm also looking for that!

**Comment by ralphtheninja** [comment]
@vweevers If we follow what @mcollina suggested, we will still support node 7 on older versions of levelup, so we can safely drop support from some versions as long as we bump major.

**Comment by MeirionHughes** [comment]
Something else to consider: at some point nodejs Buffers became backed by `Uint8Array` (4 maybe? It was improved in 8), it would make sense to have the next major levelup switch to taking a Uint8Array as `binary` then access the data via `binary.buffer`, that way you get support for passing through `Buffer` too.

**Comment by vweevers** [comment]
@ralphtheninja we can close this, no? The strategy is working well.

**Comment by ralphtheninja** [comment]
Yap!
