### ISSUE TITLE
public levelup rc testing

### ISSUE THREAD

**Issue by juliangruber** [Level/levelup#472]
We should get as many people as possible to test `levelup@2.0.0-rc1`.

I'm thinking the following:

- [x] tweet about it: https://twitter.com/juliangruber/status/907246400194441217
- [ ] test libs
  - [x] ~~level-sublevel~~ subleveldown
  - [x] pouchdb
  - [ ] browserify-fs
  - [ ] merkle-patricia-tree
  - [ ] dynalite
  - [ ] mosca
  - [ ] hard-source-webpack-plugin
  - [ ] gittoken-api-middleware
  - [x] secure-scuttlebutt
- [x] test apps
  - [x] Voltra

**Comment by ralphtheninja** [comment]
@juliangruber Maybe check projects on npm with rather frequent downloads that are based on levelup?

**Comment by ralphtheninja** [comment]
https://www.npmjs.com/browse/depended/levelup

Maybe `pouchdb`?

**Comment by juliangruber** [comment]
> @juliangruber Maybe check projects on npm with rather frequent downloads that are based on levelup?

Great idea! Didn't check downloads, but those stood out to me:

- pouchdb (dough of course)
- mosca
- levelgraph

**Comment by juliangruber** [comment]
But yeah let's rather write a script that checks download numbers. Or is there an interface for this already?

**Comment by juliangruber** [comment]
https://twitter.com/juliangruber/status/905149153810010112

**Comment by vweevers** [comment]
https://github.com/addaleax/npm-get-top-dependents

**Comment by ralphtheninja** [comment]
I think we should release an rc1 of level as well, before tweeting about it and check projects using it. In theory it's the easiest module to upgrade since it takes care of the details.

**Comment by ralphtheninja** [comment]
@juliangruber You could also take a look at some of the `nice-registry` modules, e.g. https://github.com/nice-registry/download-counts

**Comment by ralphtheninja** [comment]
@zeke How would you approach something like this? For example quering for modules that depend on `level` or `levelup` and maybe sort them based on download count?

**Comment by zeke** [comment]
> How would you approach something like this?

```sh
git clone https://github.com/nice-registry/native-modules
cd native-modules
$EDITOR lib/check-package.js # customize for levelup
npm install
npm run collect
```

Then tweak `render.js` while the collector runs. Takes an hour or two usually.

At any time while the collector is running:

```
npm run render
```

> sort them based on download count?

Yeah you could sort by [download-count](http://ghub.io/download-count) or [dependent-count](http://ghub.io/dependent-count).

The stats in those packages are out of date, but they should provide a good approximation of popularity. @kikobeats actually inspired me this week to dust off `download-counts` and start working on a way to keep it automatically updated, so that should be done soon™...

**Comment by ralphtheninja** [comment]
https://github.com/Level/level/pull/52

**Comment by ralphtheninja** [comment]
@zeke So this would limit the query to native modules only right? If so, we prob want to check _all_ modules (stand alone modules or applications).

> The stats in those packages are out of date, but they should provide a good approximation of popularity.

Getting some rough estimates is perfectly fine!

**Comment by doowb** [comment]
I've been using this for a while to get the dependents of a module and the download counts:

https://github.com/doowb/dependents-cli

```sh
npm i -g dependents-cli
dependents levelup
```

[This gist](https://gist.github.com/doowb/136595af11f90363159262c48e6bc3e0) has the results from running that. It also show the version of levelup being used in that dependent.

**Comment by ralphtheninja** [comment]
@doowb Cool! I just tried out `dependents levelup --format json` and `dependents level --format json` and it works really well.

`levelup` is used more than `level` by far

@juliangruber Going to take some work to change that :)

**Comment by juliangruber** [comment]
Nice, dependents-cli is exactly it!

I extended the list in the opening post, does that sound good to all?

**Comment by ralphtheninja** [comment]
Correction: `level` is used by more modules but dependents of `levelup` has more downloads

**Comment by ralphtheninja** [comment]
Fwiw. I think apps are easier to test than libraries. @juliangruber Tried it with voltra yet?

**Comment by zeke** [comment]
cc @0x00A

**Comment by ralphtheninja** [comment]
v2.0.0-rc2 is out

**Comment by juliangruber** [comment]
Tweeted about new level: https://twitter.com/juliangruber/status/907246400194441217

**Comment by MeirionHughes** [comment]
I've added a repo to track compatible libs / adapters / plugins / etc as I didn't see a repo already doing this. 

Is there a need to mark version compatibility (of third-party libs) with LevelUP major versions?

**Comment by juliangruber** [comment]
I think modules should still be compatible with levelup@2 as long as they don't instantiate their own database instance (it gets passed in) and they don't omit any callbacks from async methods.

**Comment by MeirionHughes** [comment]
I will cc the guys that did the typings on definatly-typed for levelup when rc3 + typings is published and they can try it.

**Comment by ralphtheninja** [comment]
> I will cc the guys that did the typings on definatly-typed for levelup when rc3 + typings is published and they can try it.

@MeirionHughes Just need to bump `memdown` dev-dep and we should be good to go?

**Comment by MeirionHughes** [comment]
need a patch on memdown first to have npm include the `memdown.d.ts` file on publish

**Comment by ralphtheninja** [comment]
Oh right. Doh, sorry.

**Comment by ralphtheninja** [comment]
I can fix.

**Comment by MeirionHughes** [comment]
@blittle @tarruda as you are listed on definatly-typed as editors for levelup@1 typings; I'd welcome a [review of the new bundled types](https://github.com/Level/levelup/blob/master/lib/levelup.d.ts) in @2

**Comment by juliangruber** [comment]
I tested `level@2.0.0-rc1` in voltra and nothing needed to be changed!

**Comment by ralphtheninja** [comment]
@juliangruber I so want to push the button for `2.0.0` and get it over with :wink:

**Comment by juliangruber** [comment]
I'm 100% for that!

**Comment by MeirionHughes** [comment]
@ralphtheninja possibly may need to change the typings for the batch stuff; especially with regard to level-sublevel (cc @dominictarr) because it has extra properties for the batch items.

**Comment by tarruda** [comment]
> @blittle @tarruda as you are listed on definatly-typed as editors for levelup@1 typings; I'd welcome a review of the new bundled types in levelup@2

Why are `T*Options` passed as type parameters and not explicitly defined interfaces?  Even if you'd like to allow users to create extensions, it still seems better to have explicit base option types that users can extend.

Also, why are `TKey`/`TValue` are type parameters to abstract leveldown even though leveldown only supports Buffer/string as keys and values? I suggest to have a look at leveldown DefinitelyTyped definitions for some ideas on how to be more strict: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leveldown/index.d.ts .

An extra suggestion for levelup2 API change/addition, even though I think it would be too late at this point: Since we are changing to a promise-based API for get/put/del, why not also have a promise-based API for reading/processing bulk data? For example, here's a snippet of some interfaces I use in a project (omitted the get/put/del APIs):

```ts
export interface DB<TK, TV> {
    iterate(opts?: QueryOptions<TK>): Promise<Cursor<TK, TV>>;
}
export interface Cursor<TK, TV> {
    nextRecord(): Promise<[TK, TV]>;
}
```

This query API wraps over levelup streaming API and allows usage like this:

```ts
async function printData () {
  const cursor = await db.iterate()
  for (;;) {
    const [key, value] = await cursor.nextRecord()
    console.log(key, value)
  }
}
```

This is implemented by wrapping levelup streaming API into something that lazily fetch rows by -once-listening to `"readable"` and `"end"` events (to simplify cleanup), but it would be simpler to wrap directly over leveldown iterator API.

**Comment by MeirionHughes** [comment]
> Why are T*Options passed as type parameters and not explicitly defined interfaces? Even if you'd like to allow users to create extensions, it still seems better to have explicit base option types that users can extend.

The main reason is because `levelup` is basically a proxy for whatever you pass to it and all options are passed the underlying db.  So the typings for levelup methods need to come from the base db. Having the generics means typescript can infer those options automatically. For example, if you do: 

```ts
let db = levelup(encode(leveldown('./db')));
```

then db is typed: 
```ts
type DbType = levelup.LevelUp<
  any,
  any,
  leveldown.LevelDownOptions,
  leveldown.LevelDownPutOptions & encoding.CodecOptions,
  leveldown.LevelDownGetOptions & encoding.CodecOptions,
  leveldown.LevelDownDeleteOptions & encoding.CodecOptions,
  leveldown.LevelDownIteratorOptions<any, any> & encoding.CodecOptions,
  leveldown.LevelDownBatchOptions & encoding.CodecOptions>
```

Or if you use RocksDB instead, without using the `encode` adapter. 

```ts
type DbType = levelup.LevelUp<
  any,
  any,
  rocksdb.RocksDbOptions,
  rocksdb.RocksDbOptions,
  rocksdb.RocksDbGetOptions,
  rocksdb.RocksDbDeleteOptions ,
  rocksdb.RocksDbIteratorOptions<any, any,
  rocksdb.RocksDbBatchOptions
```

> Also, why are TKey/TValue are type parameters to abstract leveldown even though leveldown only supports Buffer/string as keys and values? 

I guess potentially an argument could be made that any new abstract-leveldown could accept different types other than Buffer / string (i.e. typed arrays). Having the generics also comes back to getting levelup correctly typed via inference. 

There are some short comings with all this though; [as outlined here](https://github.com/Level/levelup/issues/485). 

>  I suggest to have a look at leveldown DefinitelyTyped definitions for some ideas on how to be more strict: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leveldown/index.d.ts .

with regard to leveldown itself, I could remove the ability to retype TKey and TValue and implement `AbstractLevelDown<string | Buffer, string | Buffer, ... >`, and also simplify the iterator typing too.

**Comment by juliangruber** [comment]
> @ralphtheninja possibly may need to change the typings for the batch stuff; especially with regard to level-sublevel (cc @dominictarr) because it has extra properties for the batch items. that said, sublevel looks like it consumes a levelup instance - so in theory it could use different types entirely.

This is a huge warning sign to me, the typings shouldn't be a problem for a single module consuming levelup.

**Comment by juliangruber** [comment]
@ralphtheninja we should hold off the release.

Also I wouldn't be interested in having to do a new major release when typings change.

What about this instead: We publish a separate level*-typed and only publish officially once this is stable.

**Comment by MeirionHughes** [comment]
@juliangruber currently if you simply use `level-sublevel` without `@types/level-sublevel` it works perfectly fine. However, because `level-sublevel` is [currently typed with the levelup@1 types off dt ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/924fafffc09cfeb0267573af2c847cdbfcfa464d/types/level-sublevel/index.d.ts), it will break for anyone using typescript if they switch up to levelup@2. 

![image](https://user-images.githubusercontent.com/3584509/30539374-049f3406-9c6a-11e7-810b-a48cc45d4336.png)

What I can possibly do is add all these old levelup@1 types from dt in to levelup@2's namespace as aliases, and hopefully not break anything for ts users.

**Comment by MeirionHughes** [comment]
okay; I've mitigated the typings with a non-breaking change so that it plays nice with the current `level-sublevel` typings

```ts
import 'levelup-async-iterator';
import * as levelup from 'levelup';
import * as leveldown from 'leveldown';
import * as encode from 'encoding-down';
import * as Sublevel from 'level-sublevel';

let up = levelup(encode(leveldown('./db')))
let db = Sublevel(up);
let sub = db.sublevel('stuff');

async function main() {
  //put a key into main!  
  await new Promise(r => db.put("john", "doe", r));
  //put a key into the sub-section!  
  await new Promise(r => sub.put("hello", "world", r));

  await new Promise(r =>
    db.batch([{ type: 'put', key: 'mike', value: 'powers' }], r));

  await new Promise(r =>
    sub.batch([{ type: 'put', key: 'jane', value: 'doe' }], r));

  let iter = up.iterator();

  for await (let [key, value] of iter) {
    console.log(key, value);
  }
}

main();
```

```ts
D:\Code\playground>ts-node --harmony_async_iteration main.ts
!!john doe
!!mike powers
!stuff!hello world
!stuff!jane doe
```

**Comment by MeirionHughes** [comment]
@ralphtheninja @juliangruber 

>What about this instead: We publish a separate level*-typed and only publish officially once this is stable.

I'm also leaning toward the idea of pulling out the typings into separate packages until they're stable and all third-party stuff has had a chance to upgrade. I _really_ don't want to be the one that causes friction on such a large library base. 

Its not a big deal for end-users, installing would just be: 

```
yarn add levelup
yard add levelup-typings -D
```

when everything is stable you could potentially merge it back on the next major version. 

that said;[ with compatible typings sublevel](https://gist.github.com/MeirionHughes/042d257a2607b31f5ce9c95e85330f76) can also be fully typed and inferred from the base db chain... 

![image](https://user-images.githubusercontent.com/3584509/30548111-27f3b8ea-9c89-11e7-899b-99bf955bdaa7.png)

**Comment by MeirionHughes** [comment]
I think its a case of whether you're happy to wait a little longer before releasing v2, give people a few weeks to upgrade to the new way of doing things, and give feedback on v2 (and typing).  

If you want to pull the trigger right now, then I'd say the types would need to be separated out. 

That said, I'm in the process of getting a few minor prs ready that will resolve the remaining concerns I have with the Batch and Iterator Options. I've also added in some of the legacy types from version 1 types. So `level-sublevel` _will still compile and run_ without any changes.

**Comment by juliangruber** [comment]
we can also just release v2.1 with the typings, they don't _need_ to be added just for v2

**Comment by ralphtheninja** [comment]
> we can also just release v2.1 with the typings, they don't need to be added just for v2

If we go this route, should we remove the current typings?

**Comment by juliangruber** [comment]
I agree, let's remove the typings, just push what we have right now to a branch.

**Comment by juliangruber** [comment]
> However, we should put some work into the README before the release imo.

Which readme's exaclty? There's two entry points (levelup and level), I feel already that is confusing. In the end, a docs web page would be super sweet.

**Comment by ralphtheninja** [comment]
> Which readme's exaclty? There's two entry points (levelup and level), I feel already that is confusing. In the end, a docs web page would be super sweet.

@juliangruber Imo both `level` and `levelup` readmes. But I like the idea of a docs web page. I think we should spend some time on `leveldb.org` page. Make it super clean.

**Comment by ralphtheninja** [comment]
I'm releasing `2.0.0` today if no one is against it!

**Comment by ralphtheninja** [comment]
@juliangruber Also see https://github.com/Level/level/issues/9

**Comment by MeirionHughes** [comment]
@juliangruber could you try a custom encoder with the latest + rc. I'm not sure where I'm going wrong here: 

```js
const leveldown = require('leveldown');
const encoding = require('encoding-down')
const levelup = require('levelup');

let db = levelup(
  encoding(leveldown('./db'), {
    keyEncoding: {
      encode: (a) => a.name,
      decode: (b) => { return { name: b } },
      type: "name",
      buffer: false
    }
  })
)

async function main() {
  await db.put({ name: "Hello" }, "World");
  let result = await db.get({ name: "Hello" });
  
  console.log(result);
}

main();
```

>(node:21000) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection
 id: 1): WriteError: key cannot be `null` or `undefined`

node v8.5.0

**Comment by ralphtheninja** [comment]
If I do:

```js
const leveldown = require('leveldown');
const encoding = require('encoding-down')
const levelup = require('levelup');

let db = levelup(
  encoding(leveldown('./db'), {
    keyEncoding: {
      encode: function (a) { return a.name },
      decode: function (b) { return { name: b } },
      buffer: false,
      type: "custom"
    }
  })
);

db.on('ready', () => {
  async function main() {
    await db.put({ name: "Hello" }, "World");
    await db.get({ name: "Hello" });
  }
  main().catch(console.log);
})
```

then it works, so there's some problems with deferred-leveldown (haven't found the exact problem yet)

**Comment by ralphtheninja** [comment]
@MeirionHughes I _think_ I know why this happens. Before the database is opened, `deferred-leveldown` defers the put operation, but it calls `abstract-leveldown#put` which does this

```js
key = this._serializeKey(key)
```

Which fucks up the `key` if it's an object and works well if it's a buffer or a string.

**Comment by ralphtheninja** [comment]
Just made this quick hack:

```js
DeferredLevelDOWN.prototype._serializeKey = function (key) {
  return key
}

DeferredLevelDOWN.prototype._serializeValue = function (value) {
  return value
}
```

and then it works fine. But not sure if this is the right approach and/or if it will mess up something else.

**Comment by vweevers** [comment]
> But not sure if this is the right approach

I think it is, because `deferred-leveldown` is merely a layer (like `encoding-down`, which also has identity functions for `_serialize`) in between levelup and actual storage and so should not do any serialization.

Surprised this problem didn't popup until now.

**Comment by MeirionHughes** [comment]
> Surprised this problem didn't popup until now.

At least I contributed something useful. 😁

**Comment by vweevers** [comment]
@ralphtheninja but why does it throw `key cannot be null or undefined` if the key is `'[object Object]'`?

**Comment by ralphtheninja** [comment]
@vweevers I think because when the deferred operation is actually run, then `encoding-down` till try the custom encoding and do

```
> '[object Object]'.name
undefined
```

**Comment by vweevers** [comment]
Ah that makes sense 👍

**Comment by ralphtheninja** [comment]
> At least I contributed something useful. :grin:

Awesome that you found this.

> I think it is, because deferred-leveldown is merely a layer (like encoding-down, which also has identity functions for _serialize) in between levelup and actual storage and so should not do any serialization.

Aye. So maybe it should be ok to add `._serializeKey()` and `._serializeValue()` that are no-ops.

> Surprised this problem didn't popup until now.

We clearly haven't tested it enough. We should write some tests for it. Both in `deferred-leveldown` and in `levelup`.

**Comment by MeirionHughes** [comment]
I've also noticed one of the tests isn't failing on old usage: 

https://github.com/Level/levelup/blob/master/test/create-stream-vs-put-racecondition.js#L74
https://github.com/Level/levelup/blob/master/test/create-stream-vs-put-racecondition.js#L83

this was picked up by typescript via vscode.

**Comment by ralphtheninja** [comment]
@MeirionHughes Nice catch. We could do some sanity check on the `db` parameter in the levelup constructor, e.g. assert that it's not a string, which would make these tests fail and then we rewrite the tests.

**Comment by MeirionHughes** [comment]
@ralphtheninja that test doesn't fail because it doesn't run: file is `create-stream-vs-put-racecondition.js` and the runner looks for `-test.js`

**Comment by ralphtheninja** [comment]
@MeirionHughes Would you mind making a separate issue for this? These threads have a tendency to get really long and contain multiple discussions. I have been traveling and haven't had the time to deal with the latest updates, but I will catch up on it this week.

**Comment by vweevers** [comment]
Doesn't matter anymore now, or at all, but just a cool thing. We *could have had* an rc badge. 😿 

```
![npm (rc)](https://img.shields.io/npm/v/levelup/rc.svg)
```

![npm (rc)](https://img.shields.io/npm/v/levelup/rc.svg)
