### ISSUE TITLE
Add iterator(options) and return [Symbol.asyncIterator]

### ISSUE THREAD

**Issue by MeirionHughes** [Level/levelup#477]
I'd like to propose adding a method to `levelup` that would allow direct iteration of the underlying `store.iterator`. This would negate the need for consumers to convert the `ReadStream` to an Iterable. 

from a usage perspective, something along the lines of: 

```ts
async function main(){
  let db = levelup(encode(leveldown()));

  await db.put("foo", "hello");
  await db.put("bar", "world");

  let search = db.read( { leq: "bar", limit: 10 });

  for await (let data of search){
    let key = data.key;
    let value = data.value;
  }
}
``` 

not a huge change to implement this: 

```js
LevelUP.prototype.read= function (options) {
  options = extend({ keys: true, values: true }, options)
  if (typeof options.limit !== 'number') { options.limit = -1 }
  return new LevelAsyncIterator(this.db.iterator(options), options)
}
```

where `LevelAsyncIterator` can be the stream iterator butchered to remove the Stream aspects and simply implement `[Symbol.asyncIterator]` instead - along with ability to end (clean) the underlying `store.iterator`

~~If people are happy with this proposal I can make the PRs and a new `level-iterator` repo, based off `level-stream-iterator`?~~

I'll do it as a plugin to levelup due to `Symbol.asyncIterator` being still stage-3.

**Comment by MeirionHughes** [comment]
admittedly, you could probably do this without the change: 

```
async function main(){
  let store = encode(leveldown('/path/to/db')))
  let db = levelup(store);

  let search = new LevelIterator(store, { keys: true, values: true, leq: "bar", limit: 10 });
```

**Comment by ralphtheninja** [comment]
Would it be possible/feasible to implement something on top of a `ReadableStream`? E.g.

```js
async function main(){
  const db = levelup(encode(leveldown()))

  await db.put("foo", "hello")
  await db.put("bar", "world")

  const search = new ReadableStreamIterator(db.createReadStream({ leq: "bar", limit: 10 }))

  for (let data of search) {
    let key = data.key
    let value = data.value
  }
}
```

This goes against your suggestion but also makes it more generic if it can operate on top of _any_ `ReadableStream`.

**Comment by vweevers** [comment]
See also: support of `Symbol.asyncIterator` in Node.js streams (https://github.com/nodejs/readable-stream/issues/254).

@mcollina @calvinmetcalf any thoughts? Until `Symbol.asyncIterator` lands in Node, do you think levelup should support it on its own? Not through streams, but a lower-level interface. Could be an interesting experiment, also re: performance. Easier to optimize I reckon, without a stream in the middle.

**Comment by MeirionHughes** [comment]
You can convert a stream to an asyncIterator, but you potentially have to buffer the stream if it produces faster than the consumer. I don't think this solution, because the stream is redundent to using the underlying iterator directly and exposing it via `Symbol.asyncIterator`;

Problem with `Symbol.asyncIterator` bar the fact its still stage-3, is that I doubt you'll see it in the wild without polyfill for a good few years. So I don't recommend adding it to `levelup`.

SO..  I'm just writing a plugin to _augment_ the levelup prototype and give you direct access the iterator, via asyncIterator. Those that want it can just import and use it.  Then at a later stage it can be merged into levelup. 

I can update the levelup typings to allow merging definitions with third-party plugins to levelup, so the `read()` method will show up.

**Comment by vweevers** [comment]
> Problem with Symbol.asyncIterator bar the fact its still stage-3, is that I doubt you'll see it in the wild without polyfill for a good few years. 

We can dream :)

> SO.. I'm just writing a plugin to augment the levelup prototype and give you direct access the iterator, via asyncIterator. Those that want it can just import and use it. Then at a later stage it can be merged into levelup.

👍 

Instead of `read()`, why not `iterator()`? In the future, levelup can perhaps expose `iterator(options)` which simply returns `this.db.iterator(options)`, and then we implement `Symbol.asyncIterator` in `abstract-leveldown`. If that makes sense.

And instead of key-value objects, yield arrays, e.g.:

```js
const db = levelup(leveldown('./db'))

for await (let [key, value] of db.iterator()) {
    console.log(key, value);
}
```

Just spitballing, say we add `Iterator.prototype.seek`, could still work:

```js
const db = levelup(leveldown('./db'))
const iter = db.iterator()

for await (let [key, value] of iter) {
  if (key == 'something to skip') {
      iter.seek('yonder')
  }
}
```

**Comment by MeirionHughes** [comment]
Yes, ultimately you'd want this in the abstract iterator. But, again, I wouldn't recommend you do this yet. 

Sounds good, I'll change what I've got and get some tests going.

**Comment by ralphtheninja** [comment]
@vweevers I've never seen the `for await` construct before. Where can I read more about it?

**Comment by MeirionHughes** [comment]
https://github.com/tc39/proposal-async-iteration

**Comment by vweevers** [comment]
It is also available in node 7+ with the `--harmony-async-iteration` flag.

**Comment by vweevers** [comment]
@ralphtheninja a contrived example:

```js
'use strict'

// Run with: node --harmony-async-iteration example.js

async function example() {
  for await(let [key, value] of new AbstractIterator()) {
    console.log('%s: %s', key, value)
  }

  console.log('done!')
}

class AbstractIterator {
  [Symbol.asyncIterator]() {
    const pairs = [
      ['key1', 'foo'],
      ['key2', 'bar']
    ]

    return {
      next() {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            const kv = pairs.shift()
            resolve({ value: kv, done: !kv })
          }, 500)
        })
      }
    }
  }
}

example()
```

**Comment by ralphtheninja** [comment]
> this might help if you want to try it: https://stackoverflow.com/questions/43694281/ts2318-cannot-find-global-type-asynciterableiterator-async-generator

Upvoted! :wink:

**Comment by ralphtheninja** [comment]
@vweevers What about the syntax for the `AbstractIterator`?

```js
class AbstractIterator {
  [Symbol.asyncIterator]() { // <-- this one!
    return {
      next() {
        // ..
      }
    }
  }
}
```

**Comment by vweevers** [comment]
http://2ality.com/2015/02/es6-classes-final.html#computed-method-names. Sans classes you'd write:

```js
AbstractIterator.prototype[Symbol.asyncIterator] = function() {
  return //..
}
```

**Comment by MeirionHughes** [comment]
@vweevers one hickup with 
```ts
let db = levelup(encode(leveldown('./db')));
let iter = db.iterator();  
for await (let [key, value] of iter) {
  if (key == 'something to skip') {
      iter.seek('yonder')
  }
}
```
is that `skip` is not a function on `encoding-down`'s iterator. You'd need a way to pass through function calls not present on an iterator instance, to the encapsulated iterator, for each iterator.

**Comment by vweevers** [comment]
Oh yes, it was just an illustration; `seek` is not currently exposed, and only implemented in leveldown. Sorry if I wasn't clear.

**Comment by MeirionHughes** [comment]
released: https://www.npmjs.com/package/levelup-async-iterator

**Comment by vweevers** [comment]
Too much awesome stuff!

**Comment by MeirionHughes** [comment]
Looks like async iteration is going stable - it is shipped in V8 - so hopefully we'll see it without flags in node 9 
https://github.com/tc39/proposal-async-iteration/issues/63#issuecomment-330978069

**Comment by calvinmetcalf** [comment]
there is a good chance streams will support async iteration so that's probably a good direction to go in

**Comment by zixia** [comment]
+1

**Comment by vweevers** [comment]
Breaking this down:

- Add `levelup#iterator`: #586
- Add `iterator#seek`: Level/abstract-leveldown#234
- Implement multiget using `levelup#iterator` and `iterator#seek` (in userland to start) (#491)
- Add `[Symbol.asyncIterator]` to abstract iterator: Level/abstract-leveldown#235
- Add `[Symbol.asyncIterator]` to streams: will land soon in `readable-stream`.
