### ISSUE TITLE
InitializationError: Must provide a location for the database

### ISSUE THREAD

**Issue by pefish** [Level/levelup#489]
I got this error. Here is my code

const db = levelup(enc(leveldown('./testdb')));

please help

**Comment by ralphtheninja** [comment]
@pefish Use `level` instead

```js
const level = require('level')
const db = level('./testdb')
```

**Comment by pefish** [comment]
@ralphtheninja  thanks, it works

**Comment by 0x530302** [comment]
For everyone, who does not want to use `level` for some reason:

Most of the documentation has already been updated for levelup's 2.0 release, which is at the time of writing only available as a pre-release on npm. As soon as the 2.0 is released, the above `const db = levelup(enc(leveldown('./testdb')));` should work.

Until then the following code should work:
```
const db = levelup('./testdb', { db: leveldown });
```

**Comment by ralphtheninja** [comment]
@0x530302 Thanks for clarifying this. It's a bit unfortunate that the current master branch is showing docs for the coming release. I'll focus on the README this week and hopefully get 2.0.0 out asap.

**Comment by ralphtheninja** [comment]
Added to milestone just as a reminder to close it once 2.0.0 is released

**Comment by fergiemcdowall** [comment]
This is still not updated in the README (as far as I can see)
