### ISSUE TITLE
npm levelup@1.3.9 not surport promise

### ISSUE THREAD

**Issue by yugame** [Level/levelup#490]
LevelUP.prototype.get = function (key_, options, callback) {
  var self = this
  var key

  callback = getCallback(options, callback)

  if (maybeError(this, options, callback)) { return }

  if (key_ === null || key_ === undefined || typeof callback !== 'function') {
    return readError(this, 'get() requires key and callback arguments', callback)
  }

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
the new code  is surport

LevelUP.prototype.get = function (key, options, callback) {
  if (key === null || key === undefined) {
    throw new ReadError('get() requires a key argument')
  }

  var promise

  callback = getCallback(options, callback)

  if (!callback) [ callback, promise ] = promisify()

  if (maybeError(this, callback)) { return promise }

  options = getOptions(options)

this.db.get(key, options, function (err, value) {



hope update the npm

**Comment by MeirionHughes** [comment]
version 2 contains the promise based API, but is tagged beta. install explicitly with: `npm install levelup@2.0.0-rc3`

**Comment by KMCGamer** [comment]
@MeirionHughes Is levelup@2.0.0-rc3 supposed to return Buffer objects when using the promises or is that just a beta thing at the moment?

Using:
```javascript
const db = levelup(leveldown('data'));
// write then read
async function wr() {
  await db.put('asdf', 'jkl');
  console.log(await db.get('asdf'));
}
wr();
```
gives me: `<Buffer 6a 6b 6c>` in the console.

**Comment by yugame** [comment]
thank you 
use pomise and async is cool
