### ISSUE TITLE
Move or remove setMaxListeners(Infinity)

### ISSUE THREAD

**Issue by huan** [Level/levelup#493]
https://github.com/Level/levelup/blob/091cd95bb1736a5e365b69f7ee3d8299c8f02599/lib/levelup.js#L39

I'd like to suggest using a big number(like `42`) instead of `Infinity` at here because `Infinity` will make it hard to notice of `addListener` memory leak.

**Comment by vweevers** [comment]
That number would be kind of arbitrary (though the default Node.js limit is too).

cc @juliangruber seeing as you added this in bae8af68e14216a5bfefe11e201ef38889bc5ae8.

**Comment by vweevers** [comment]
Prior discussion: #47.

**Comment by juliangruber** [comment]
@zixia did you notice this reading the code or did you have an actual memory leak?

**Comment by zixia** [comment]
@juliangruber I notice this by reading the code.

The memory leak might happen if user code has some bug outside the levelup library.

For example, if I use levelup as my db, and run my function lots of times which include `db.on('event', cb)` by mistake,  then I should get a warning. But if we set maxListeners to `Infinity`, the warning will never show.

**Comment by juliangruber** [comment]
Ok, I understand. I have two ideas:

1) since this hasn't caused an actual error yet, at least not one that we're aware of, let's keep it like this until it becomes a reported issue
2) Remove the setMaxListeners and use a different abstraction for the same task, or even just a separate event emitter with infinite listeners

**Comment by zixia** [comment]
I vote for the second idea: remove the setMaxListeners.

Currently, I do the following in my code to prevent the future mistakes: `this.levelDb.setMaxListeners(17)  // default is Infinity`

https://github.com/zixia/face-blinder/blob/38ba45f263cc5cd892d034f8b115b470ed30bf0e/src/store.ts#L31

**Comment by vweevers** [comment]
@juliangruber as I understand it, this was added because levelup deferred operations with `once('ready')`? That's now handled by `deferred-leveldown`, so why do we still need `setMaxListeners(Infinity)`?

**Comment by juliangruber** [comment]
@vweevers deferred-leveldown will for each queued async method call `db.open`, which itself then adds a listener for the `'open'` event: https://github.com/Level/levelup/blob/master/lib/levelup.js#L80.

So we do still need some way to prevent the warning here.
