### ISSUE TITLE
What happened to ChainedBatch.write(options)?

### ISSUE THREAD

**Issue by MeirionHughes** [Level/levelup#496]
The abstract down interface accepts options on the `write` method: https://github.com/Level/abstract-leveldown/blob/master/abstract-chained-batch.js#L67. 

However, levelup does not: https://github.com/Level/levelup/blob/master/lib/batch.js#L56

Is this deliberate?

**Comment by ralphtheninja** [comment]
Good questions. A chained batch on the levelup side should end with a `.write()`, see https://github.com/Level/levelup#batch_chained, which never had any options parameter.

I forget why `.write()` in `abstract-chained-batch.js` even has options. It seems to me that if `._write()` function exists, we will always call that one, and if not we do `this._db._batch(..)`, see https://github.com/Level/abstract-leveldown/blob/master/abstract-chained-batch.js#L79-L83

**Comment by MeirionHughes** [comment]
The typings for level@1 [actually have the options on _some_ operations](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f3b9cb6f5173c36695c4d3cb39a950c6448ddaf2/types/levelup/index.d.ts#L60-L67) (why only del and not put, I don't know - probably bad typings?):

**Comment by vweevers** [comment]
Options were added in https://github.com/Level/levelup/pull/604.
