### ISSUE TITLE
Question: What's the best way to handle multiple handles open at once?

### ISSUE THREAD

**Issue by austinfrey** [Level/levelup#510]
I've looked at `multilevel` and `level-party` for this, but I'm not sure they are the correct solution. I'd like to know the best way to handle opening multiple handles in a levelDB instance without doing so over the network. For example, if I wanted to access the same db instance from multiple applications locally, not over the network, how hard would that be? 

Would it be acceptable to just check if the resource is busy, if yes, try again later, if no go ahead with the operation? Or should I be looking for a way to have multiple handles open at once? Maybe you can do that with `level-party` but my understanding was that it was for use over the network. 

Thanks in advance.

**Comment by vweevers** [comment]
`level-party` is the right answer; it uses unix sockets (no network involved) or named pipes on Windows.

While `multilevel` shares a db over the network, `level-party` shares it between processes.

**Comment by austinfrey** [comment]
@vweevers, perfect! Thanks for the feedback
