### ISSUE TITLE
JSON valueEncoding / keyEncoding no longer referenced on the README?

### ISSUE THREAD

**Issue by rook2pawn** [Level/levelup#513]
Curious as to why this is? I noticed the change here 
https://github.com/Level/levelup/commit/8a58d6a08104f11ba5f230402ae76560a18bd49e#diff-04c6e90faac2675aa89e2176d2eec7d8L154

And options is referenced but not linked as to what kind of options are available.

**Comment by vweevers** [comment]
Encodings are no longer builtin since levelup v2, instead handled by `encoding-down`. Please see [CHANGELOG.md](https://github.com/Level/levelup/blob/master/CHANGELOG.md) for an upgrade guide. Though it is lacking an example of `key/valueEncoding` (so let us know if you need help).

**Comment by rook2pawn** [comment]
options as mentioned in the second bullet point https://github.com/Level/levelup#levelupdb-options-callback could be linked to encoding-down, perhaps with a small example.. should i submit a pr?

**Comment by ralphtheninja** [comment]
> And options is referenced but not linked as to what kind of options are available.

Maybe we should clarify that `options` are passed to the underlying store when it's opened and that `options` are backend specific

**Comment by vweevers** [comment]
> and that options are backend specific

yes, this. 👍

**Comment by vweevers** [comment]
@rook2pawn we did two things:

- Clarified that options are specific to the underlying store (#514)
- Added integration examples to the store in question: [`encoding-down`](https://github.com/level/encoding-down#usage).

Does that help?
