### ISSUE TITLE
leveldb files repair, but over repaired

### ISSUE THREAD

**Issue by ijunaid8989** [Level/levelup#520]
We had a hardisk with an XFS filesystem, and there were tons of leveldb files, we were using alongside with SeaweedFS, Our Disk got crashed and we mounted and unmounted it.. then did an xfs_repair -L..

But after that, leveldb idbs got corrupt, 

we tried a python script, very simple as
import leveldb;
leveldb.Repair("path to db folder, where there are all ldbs files are");

It solved our problem, but It over solved it.. We only wanted to repair the corrupt files, NOT RECOVER the old files, 

but that repair just recovered everything which was ever deleted from the filer folder..

Is there any way or any option in leveldb repair, where we can mention, not to recover the old files, just repair them, I heard about a --repair option but I dont know what is the use of it

Or is there anyway, so we can be deleted the extra files, which are not necessary? like we only need to repair files not recover them

**Comment by vweevers** [comment]
Apologies for the late response. This seems to be about LevelDB rather than Node.js bindings for LevelDB, so I suggest asking [google/leveldb](https://github.com/google/leveldb) for advice. That said, if there is some option in LevelDB that isn't exposed in JS, feel free to open a new ticket.
