### ISSUE TITLE
Some problems with using levelup to open ethereum blockchain saved in LevelDB by Geth

### ISSUE THREAD

**Issue by gudsaf** [Level/levelup#523]
Guys, try to make [example from that manual](https://wanderer.github.io/ethereum/nodejs/code/2014/05/21/using-ethereums-tries-with-node/), but can't open LevelDB in line: 
`var db = levelup('/Users/Ololo/EthereumTestNet/geth/chaindata');`

with error 

> InitializationError: Must provide db

Also tried use another path (not just folder chaindata, *.ldb files too), but no any happy ends. What's wrong?

Use latest **Nodejs**, latest **levelup** and latest **Geth**, **Mac**

**Comment by vweevers** [comment]
Usage has changed in levelup v2.

If you want identical functionality to the blogpost you linked to, the easiest way is [`level`](https://github.com/Level/level):

```js
var level = require('level')
var db = level('./db')
```

Which is functionally equivalent to:

```js
var levelup = require('levelup')
var encode = require('encoding-down')
var leveldown = require('leveldown')

var db = levelup(encode(leveldown('./db')))
```

See also [the changelog](https://github.com/Level/levelup/blob/master/CHANGELOG.md#200--october-2017). Hope that helps :)
