### ISSUE TITLE
Follow the example of README.md and nothing happen

### ISSUE THREAD

**Issue by ruiyeah** [Level/levelup#525]
I have followed the example
```
var levelup = require('levelup')
var leveldown = require('leveldown')

// 1) Create our store
var db = levelup(leveldown('./mydb'))

// 2) Put a key & value
db.put('name', 'levelup', function (err) {
  if (err) return console.log('Ooops!', err) // some kind of I/O error

  // 3) Fetch by key
  db.get('name', function (err, value) {
    if (err) return console.log('Ooops!', err) // likely the key was not found

    // Ta da!
    console.log('name=' + value)
  })
})
```
And then nothing happened.
I tried to insert `db.isOpen()`  just below  where I created my store and it returned a result:"false".
Followed by the db's detail:
```
LevelUP {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: Infinity,
  options: { createIfMissing: true, errorIfExists: false },
  _db: LevelDOWN { location: './mydb', status: 'new', binding: Database {} },
  db:
   DeferredLevelDOWN {
     location: '',
     status: 'opening',
     _db: undefined,
     _operations: [],
     _iterators: [] 
} }

```

And my nodejs is 6.11.1 ,levelup@2.0.1 leveldown@2.1.0.

Thanks for your help!

**Comment by ralphtheninja** [comment]
> And then nothing happened.

So nothing is printed from `console.log`, i.e `name=levelup`?



> I tried to insert db.isOpen() just below where I created my store and it returned a result:"false".

This is expected since the db will open on next tick.

**Comment by ruiyeah** [comment]
@ralphtheninja  Yes.Nothing is printed from `console.log`.
And I have tried to modify the callback once:
```
db.put('name', 'levelup', function (err) {
    console.log("leveldb");
    ...
```
But it did not print anything to.

**Comment by ralphtheninja** [comment]
@ruiyeah Are you on windows?

**Comment by ruiyeah** [comment]
@ralphtheninja Yes, windows 10.

**Comment by ralphtheninja** [comment]
Can you try changing the path from e.g. `./mydb` to `mydb`? I just want to rule out the path is borked.

**Comment by ruiyeah** [comment]
I changed it to`var db = levelup(leveldown('mydb'));`,and still nothing printed out.
Is there any step I might miss,for example , mkdir 'mydb'?
I am just new to use leveldb and merely follow what the example ask me to do.

**Comment by vweevers** [comment]
> Is there any step I might miss,for example , mkdir 'mydb'?

Nah, LevelDB should create the directory if it doesn't already exist.

Assuming you placed the code in `example.js`, what is the output of:

```
node example.js || echo %errorlevel%
```

**Comment by ralphtheninja** [comment]
> Is there any step I might miss,for example , mkdir 'mydb'?

You could try, but I don't think that's the issue. It should be created by default.

@Level/owners Anyone else having similar problems on Windows?

**Comment by ruiyeah** [comment]
No output.It printed out nothing.

Well,and then I tried to delete the node_modules folder and re-execute this command `npm install`.It printed "name=levelup" sucussfully...

I am very puzzled about this. This is not my first time to reinstall the package, there aren't any error message at all.But it just print out nothing before. 

However,after I reinstall it,it worked.I haven't change the code at all,Orz.

Thanks for your help!You are so kind.

**Comment by ralphtheninja** [comment]
@ruiyeah Ok! Please re-open if you have problems again.
