### ISSUE TITLE
OpenError: IO error: ( ... path ... ) LOCK: No such file or directory

### ISSUE THREAD

**Issue by mmick66** [Level/levelup#526]
I am just trying to open a db through:
```
let LevelUP = require('levelup');
let LevelDown = require('leveldown');
let path = require('os').homedir() + '/keys.db';
let db  = LevelUP(LevelDown(path));
```
... and getting an error. The Error object traces as...
```
message: "IO error: /Users/myname/db/base.db/LOCK: No such file or directory"
```

_OS: MacOS Sierra_

**Comment by ralphtheninja** [comment]
The `/keys.db` path might be the culprit, it's an absolute path. Did you mean `./keys.db`?

**Comment by mmick66** [comment]
Can't it do absolute paths? The path traced in the error exists...

**Comment by mmick66** [comment]
I am sorry... I had not included the entirety of my source code, hence the confusion. Please have a look at my updated comment above. I have tried with other directories and the problem persists.

**Comment by vweevers** [comment]
Do you get the same error if you run your app with `sudo`?

**Comment by mmick66** [comment]
Ok.. when I run with sudo it works! 

Now... I also need to create the full path before I run the code. The library does not create the folders down the db file. If for example I pass `/data/names.db` I actually need to create the `data` folder on the root directory. Is there an automated way to do this?

**Comment by ralphtheninja** [comment]
> Is there an automated way to do this?

`leveldown` doesn't recursively create the path so you would have to do that some other way.

**Comment by mmick66** [comment]
Thank you!
