### ISSUE TITLE
key value will be always returned as the last one

### ISSUE THREAD

**Issue by pokal4u** [Level/levelup#537]
HI,

When I put value for key, I think overwrite the previous value, because when try to get key value will be always returned as the last one.

my code:

db.put('srinivas', '12345', function (err) {
	if (err) return console.log('Ooops!', err)
});

db.get('srinivas', function (err, value) {
	if (err) return console.log('Ooops!', err)
	console.log('key' + value);
});

Thanks

**Comment by ralphtheninja** [comment]
I don't understand your question. What is the problem?

**Comment by pokal4u** [comment]
I put value for key "srinivas" as 12345, then again put value as "6789".
When I get data it returns 6789 only, I need to print 12345 and 6789 how?

**Comment by MeirionHughes** [comment]
you'll need treat it as a key-bin, rather than a key-value store

```
let bin = await db.get(key) || [];
bin.push(6789);
await db.set(key, bin);
```

... or there about. you can reuse it by wrapping levelup's get and set methods.

**Comment by ralphtheninja** [comment]
@pokal4u Now I see what you mean. This is how a key-value store works.
