### ISSUE TITLE
Add to documentation how to get range of keys

### ISSUE THREAD

**Issue by kevinsimper** [Level/levelup#542]
I could not figure out clearly how to get a range of keys and I wrote a post about how to do it. Would it make sense to add it to the readme or maybe just the conclusion? I did not understand how to use `gt` and `lt` at first.
https://medium.com/@kevinsimper/how-to-get-range-of-keys-in-leveldb-and-how-gt-and-lt-works-29a8f1e11782

```
user:kevin
user:sofie
user:mike
todos:1
todos:2
todos:3
```
```
const key = 'user:'
db.createReadStream({
  gte: key,
  lte: String.fromCharCode(key.charCodeAt(0) + 1)
})
```

**Comment by vweevers** [comment]
The Resources section in [`Level/awesome`](https://github.com/Level/awesome#resources) would be the best place for this now. A [PR is welcome](https://github.com/Level/awesome#contributing)!
