### ISSUE TITLE
exposing compactRange

### ISSUE THREAD

**Issue by ttvi** [Level/levelup#554]
Hello,

We saw the `compactRange` function has been exposed on `leveldown`, we don't know the reason why it is not exposed on `levelup` but is there any chance you are thinking of it or accepting such PR?

In our company, we have a workload with a lot of writes and a lot of deletes (using `level`). From there we discovered that the compaction of leveldb does not work the way we want; it took sometimes days or more not compacting the database even with a long very light load afterward. We therefore want to control the compaction, but cannot do that as levelup does not expose `compactRange`.

Let us now if it is a possibility or if we are missing something here.

Thanks.

**Comment by ralphtheninja** [comment]
The reason is because `compactRange` is part of the `leveldown` api and it's not necessarily someting that all stores can support.

**Comment by ralphtheninja** [comment]
@ttvi As a workaround you can do:

```js
const level = require('level')                         
                                                       
level('./db', function (err, db) {                     
  db.db.db.compactRange('foo', 'foo~', function (err) {
                                                       
  })                                                   
})                                                     
```

**Comment by ttvi** [comment]
Thanks @ralphtheninja. The workaround works, though not for all versions of level.
We are looking forward to the availability of it in levelup too.
