### ISSUE TITLE
how to add comparator function

### ISSUE THREAD

**Issue by greatyaqi** [Level/levelup#555]
```
const leveldown = require('leveldown');
const db = levelup(leveldown('testDB'));
```
I want to add a custom sort key function,Where is this option?

**Comment by ralphtheninja** [comment]
Unfortunately it's not possible at the moment. See https://github.com/Level/leveldown/issues/28

**Comment by peakji** [comment]
I would recommend to use https://github.com/deanlandolt/bytewise to make you keys *naturally* sorted.
