### ISSUE TITLE
How to provoke error callback on createReadStream.

### ISSUE THREAD

**Issue by nadalfederer** [Level/levelup#558]
Hi. Here is basic code for a post/get request to levelDb. To cover code with tests I have to write provoke `error` callback. Is there any way to do it? Tried to find an example, but was not successful
![image](https://user-images.githubusercontent.com/6043510/38364892-09df91ca-38e3-11e8-854c-dab6c4c8ea84.png)

**Comment by ralphtheninja** [comment]
What about something like this?

```js
const createReadStream = db.createReadStream.bind(db)
db.createReadStream = () => {
  const stream = createReadStream()
  process.nextTick(() => {
    db.emit('error', new Error('oh noes')
  })
  return stream
}
```

**Comment by nadalfederer** [comment]
Thx.
