### ISSUE TITLE
iterator has ended error

### ISSUE THREAD

**Issue by cisaacson** [Level/levelup#559]
I am getting an `iterator has ended` error when I use `leveldown` as the engine. With `memdown` the same code works fine. 

Here is the stack trace:
```
/Users/coryisaacson/git/rtip-research/ts-index-test/node_modules/leveldown/iterator.js:51
    this.binding.next(function (err, array, finished) {
                 ^
Error: iterator has ended
    at Iterator._next (/Users/coryisaacson/git/rtip-research/ts-index-test/node_modules/leveldown/iterator.js:51:18)
    at Iterator.AbstractIterator.next (/Users/coryisaacson/git/rtip-research/ts-index-test/node_modules/abstract-leveldown/abstract-iterator.js:27:8)
```

Here are the pertinent lines of code:

```
async function writeReadTest() {
  let db;
  try {
    db = await levelup(leveldown('./db'));
    await db.put('hey', new Buffer('you'));
    ...
    await db.createReadStream()
      .on('data', function (data: any) {
        logger.d(`key: ${data.key} = value: ${data.value}`);
      })
      .on('error', function (err: Error) {
        throw err
      })
      .on('close', function () {
        logger.d(`Stream close`);
      })
      .on('end', function () {
        logger.d(`Stream end`)
      });

    await db.close();
  } catch(e) {
    logger.er(`Error: ${e} stack: ${e.stack}`)
  } finally {
    db.close();
  }    
```
It may just be my handling of the async code is incorrect, but like I said it works fine with `memdown`. Any help much appreciated.

**Comment by vweevers** [comment]
The problem is in `await db.createReadStream()`. Because `createReadStream` does not return a promise, but a stream, `await` converts it to a resolved promise. So rather than waiting for the end of the stream (after which you can safely close the `db`), it resolves immediately.

There are many solutions to this, here's one:

```js
const streamToPromise = require('stream-to-promise')
const stream = db.createReadStream()

stream.on('data', function (data) {
  logger.d(`key: ${data.key} = value: ${data.value}`);
})

await streamToPromise(stream)
await db.close()
```

**Comment by vweevers** [comment]
BTW, the same thing happens on this line:

```js
db = await levelup(leveldown('./db'))
```

It's the same as writing:

```js
db = await Promise.resolve(levelup(leveldown('./db')))
```

The good news is: you don't need it at all, as `levelup` will open the db in the background and internally queue up any operations. This means you can simply do:

```js
db = levelup(leveldown('./db'))
```

**Comment by cisaacson** [comment]
Thanks very much for the quick help.
Cory

Cory Isaacson Advisor Mobile: (818) 359-2615 http://www.agildata.com
On Mon, Apr 16, 2018 at 3:59 PM, Vincent Weevers <notifications@github.com> wrote:
BTW, the same thing happens on this line:

db =awaitlevelup(leveldown('./db'))

It's the same as writing:

db =awaitPromise.resolve(levelup(leveldown('./db')))

The good news is: you don't need it at all, as levelup will open the db in the background and internally queue up any operations. This means you can simply do:

db =levelup(leveldown('./db'))
