### ISSUE TITLE
Is it possible to read and write Sets in levelup?

### ISSUE THREAD

**Issue by fergiemcdowall** [Level/levelup#561]
Is there any way to read Sets in and out of a `levelup` instance?

```javascript
const encode = require('encoding-down')
const leveldown = require('leveldown')
const levelup = require('levelup')

const db = levelup(encode(leveldown('./mydb'), { valueEncoding: 'json' }))

db.put('myLovelySet', new Set(['one', 'two'])).then(doc => {
  db.get('myLovelySet').then(val => {
    console.log(val.has('one'))
  })
})
```

...or is it easiest to just convert everything to Arrays?

**Comment by vweevers** [comment]
With a custom encoding (that extends JSON to support Set, or an encoding that just stringifies Set), I guess you *could*. But not sure you should. If you store objects (non-primitives) in your sets, you'll lose object identity, no matter what encoding you choose.

You could also make each value of the Set a db key (which makes them unique), and use streams to put the Set back together.

Question is what you're trying to achieve.

**Comment by fergiemcdowall** [comment]
If you are working with Sets, it makes things cleaner if you can store Sets.

As you say, its fairly straight forward to store arrays of things as contiguous db keys. You can also fairly trivially cast Sets to Arrays, so plenty of workarounds exist.

**Comment by vweevers** [comment]
> If you are working with Sets, it makes things cleaner if you can store Sets.

I see that. I just wanted to note that it's not possible to keep the full semantics of Set. That only matters though if you expose the sets to a consumer of your module/app.

**Comment by fergiemcdowall** [comment]
👍
