### ISSUE TITLE
db.put('someKey', new Error('some error')) will result in storing an empty Object

### ISSUE THREAD

**Issue by jookshub** [Level/levelup#570]
Hi,

I was trying something like this:

```
const levelUp = require('levelup');
const levelDown = require('leveldown');
const encode = require('encoding-down');

const db = levelUp(encode(levelDown('./demo'), {
  valueEncoding: 'json'
}));

(async () => {
    await db.put('someKey', new Error('some error'));
    const test = await db.get('someKey');
    console.log('TEST:', test, test.message);
})();
```

but instead of the error message, this resulted in `{}`.

This however:
```
  await db.put('someKey', new Error('some error').message);
  const test = await db.get('someKey');
  console.log('TEST:', test);
```

works as expected and results in `TEST: some error`

I am using  "leveldown": "^3.0.1", and  "levelup": "^2.0.2".

Thankful for help!

**Comment by vweevers** [comment]
This is as expected. Depending on what store you use (leveldown?), it has to encode your value to one that can be stored on disk or elsewhere. If the store is wrapped with `encoding-down`, it will by default encode an error as `String(error)` which might be enough for you.

Can you share a full example?

**Comment by jookshub** [comment]
I've updated my example, hope this is a more complete picture now. As you can see, I've used `encoding-down` with JSON encoding. As https://github.com/Level/encoding-down state, storage of objects should not be a problem and it wasn't until `new Error()`, which was unexpected for me.

I guessed this might be due to some conversion problems, as `Error` is a bit troublesome (https://stackoverflow.com/q/18391212/1370465)

**Comment by vweevers** [comment]
I see. Yea, an Error is not a normal object with enumerable properties. This can be demonstrated by:

```js
var e = new Error()
Object.defineProperty(e, 'test', { enumerable: true, value: '123' })
JSON.stringify(e) // {"test":"123"}
```
