### ISSUE TITLE
remove brfs in favor of Buffer.from()

### ISSUE THREAD

**Issue by vweevers** [Level/levelup#578]
Or `browserify` will fail. Found when working on `level-js`, which has some integration tests with `levelup`. 

@ralphtheninja this might be urgent. WDYT?

**Comment by vweevers** [comment]
Though we only use `brfs` for tests, currently this transform is defined in `package.json`, which means it will always be applied.

**Comment by ralphtheninja** [comment]
If we back up a bit. Why do we need `brfs` in the first place?

**Comment by ralphtheninja** [comment]
Aha

```
lms@x260 ~/src/level/levelup (master)
$ git grep -n -C1 brfs
package.json-47-    "bl": "^2.0.0",
package.json:48:    "brfs": "~1.6.1",
package.json-49-    "browserify": "^16.0.0",
--
package.json-69-    "transform": [
package.json:70:      "brfs"
package.json-71-    ]
--
test/common.js-62-module.exports.loadBinaryTestData = function (callback) {
test/common.js:63:  // Read synchronously to avoid an issue with brfs
test/common.js-64-  var buf = fs.readFileSync(path.join(__dirname, 'data/testdata.bin'))
```

**Comment by vweevers** [comment]
We might be able to replace the fixture with a simple `Buffer.from('something')` though.

**Comment by ralphtheninja** [comment]
The best thing imo would be if we could get rid of `brfs` completely, if possible.

**Comment by vweevers** [comment]
Can you take this on? My head's full with `level-js` ;)
