### ISSUE TITLE
Greater than parses key as string, not as number

### ISSUE THREAD

**Issue by cre8** [Level/levelup#601]
I want to store blocks inside my leveldb with numeric keys. If I have blocks from 1 to 12 and request all blocks greater than 2 it will return the numbers from 3 to 9.

One solution would be to store them with 0 at the beginning like 001, 002, ... 010, ... but this will limit the amount of blocks. So is there a way to parse the key as number to compare them or have I need to use anther structure for my keys to sort them?

**Comment by cre8** [comment]
@vweevers I thought about converting the decimal to binary before saving it, but with this package everything is done automatically. Thanks for the quick answer.

**Comment by MeirionHughes** [comment]
try https://www.npmjs.com/package/bytewise, quite robust and will turn anything into a sortable Buffer

**Comment by vweevers** [comment]
@MeirionHughes compared to `lexicographic-integer`, `bytewise` is very slow. If @cre8 only needs sorted numbers, I'd recommend `lexicographic-integer`.
