### ISSUE TITLE
OpenError: IO error: ./tmp/database: Invalid argument

### ISSUE THREAD

**Issue by cre8** [Level/levelup#606]
I use level in a docker container and it worked quite well, but the last days I get an error: `(node:16) UnhandledPromiseRejectionWarning: OpenError: IO error: ./tmp/database: Invalid argument at /block/node_modules/levelup/lib/levelup.js:87:23`

The folder and files for the database are created. When I change the location to `./database` it works, but no more with a location in a subfolder.

**Comment by vweevers** [comment]
- Can you please share code and the output of `npm ls levelup leveldown`?
- Does the db reside on a Docker volume? What kind?
- Does the directory have proper permissions?
- Is the directory empty?

**Comment by cre8** [comment]
* Can you please share code and the output of npm ls levelup leveldown?
```
`-- level@4.0.0
  +-- level-packager@3.1.0
  | `-- levelup@3.1.1
  `-- leveldown@4.0.1
```
* Does the db reside on a Docker volume? What kind?
I mount a folder in the container. Other ressources from the volume are used correctly.

* Does the directory have proper permissions?
The container creates the blockchain folder so i think it has the permission for writing.

* Is the directory empty?
The tmp directory exists, but the blockchain folder will be created. Same error when I restart the program without deleting the folder.

**Comment by cre8** [comment]
@vweevers I created a repo to reproduce the steps: https://github.com/cre8/leveldb:

running `docker-compose build generator && docker-compose run generator` will result:
```
generator_1  | (node:5) UnhandledPromiseRejectionWarning: OpenError: IO error: ./tmp/mydb: Invalid argument
generator_1  |     at /block/node_modules/levelup/lib/levelup.js:87:23
generator_1  |     at /block/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
generator_1  |     at /block/node_modules/deferred-leveldown/deferred-leveldown.js:20:21
generator_1  |     at /block/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
generator_1  |     at /block/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
generator_1  | (node:5) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
generator_1  | (node:5) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
leveldb_generator_1 exited with code 0
```

**Comment by vweevers** [comment]
Ah, you're using alpine? IIRC leveldown doesn't support it, in the past I had to do `npm i --build-from-source`.

**Comment by vweevers** [comment]
See https://github.com/Level/leveldown/issues/388

**Comment by cre8** [comment]
I don't think that alpine is the problem: I used the image for some weeks and it worked pretty well. I changed the image to a normal node one:
```
FROM node:8

WORKDIR block

COPY package*.json ./

RUN npm install --build-from-source

COPY index.js .

ENTRYPOINT node index.js        
```
still the same error...

**Comment by vweevers** [comment]
OK. Well if anything, `--build-from-source` will prevent segfaults to that's one thing out of the way.

At a quick glance, your setup looks good otherwise. Will need more time to investigate.

**Comment by ralphtheninja** [comment]
@cre8 Did you manage to solve this or is this still an issue? Please re-open if needed.

**Comment by cre8** [comment]
@ralphtheninja I found a solution, but I can't remember the fixes I made to fix it...
