### ISSUE TITLE
Rewrite to typescript

### ISSUE THREAD

**Issue by wookieb** [Level/levelup#609]
Will you allow me to rewrite whole package to typescript?

**Comment by vweevers** [comment]
Short answer: no. All projects in the Level organization are written in plain JavaScript and it's safe to say the majority of users and maintainers prefer it that way. This is not gonna change. See also https://github.com/Level/abstract-leveldown/pull/204#issuecomment-367006657.

Thanks for understanding! Efforts are underway to provide DT typings, see https://github.com/Level/community/issues/16. If you have further questions about TS, feel free to ask in that thread.
