### ISSUE TITLE
Use native Object.assign instead of xtend

### ISSUE THREAD

**Issue by jimmywarting** [Level/levelup#612]
[xtend](https://github.com/Raynos/xtend) can easily be replaced with [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

This reduce the dependencies and possible also avoid duplicated versions where some package don't use the same version range for the xtend package

```js
// immutable
Object.assign({}, a, b)

// mutable
Object.assign(a, b)
```

**Comment by vweevers** [comment]
We use `xtend` for browser compat.

**Comment by jimmywarting** [comment]
Well, then can we use a polyfill instead? then browser that supports it natively would be able to garbage collect the necessary parts and use the native faster alternativ when ever possible.

https://www.npmjs.com/package/object-assign came to mind.

**Comment by vweevers** [comment]
Feel free to reopen if you know of a polyfill or ponyfill that's faster than `xtend`, or if you can prove that `Object.assign()` is significantly faster than `xtend` nowadays (in which case it might be acceptable to require consumers to include a slower polyfill for older browsers).
