### ISSUE TITLE
Support encoding options on chained batch

### ISSUE THREAD

**Issue by vweevers** [Level/levelup#633]
While we support passing `options` to `chainedBatch.write()`, `encoding-down` encodes keys and values before `write()` is called. We can keep that as-is, but should allow encoding options on `chainedBatch.put()` and `chainedBatch.del()`.

E.g.: `chainedBatch.put(key, value, options)`. 

To be added to:

- [x] `abstract-leveldown`: [7.0.0](https://github.com/Level/abstract-leveldown/releases/tag/v7.0.0)
- [x] `encoding-down`: [7.0.0](https://github.com/Level/encoding-down/releases/tag/v7.0.0)
- [x] `levelup`: https://github.com/Level/levelup/pull/717, [5.0.0](https://github.com/Level/levelup/releases/tag/v5.0.0)
- [x] `level` (just documentation): [7.0.0](https://github.com/Level/level/releases/tag/v7.0.0)

**Comment by liximomo** [comment]
Really need this

**Comment by vweevers** [comment]
Done
