### ISSUE TITLE
Can we store a object into the store?

### ISSUE THREAD

**Issue by inherithandle** [Level/levelup#638]
the documentation said: 

> put() is the primary method for inserting data into the store. Both key and value can be of any type as far as levelup is concerned.

when I tried it, I cannot get a object as a value. the only I got is a object with 
```
{
            0 : '[',
            1 : 'o',
            2 : 'b',
            3 : 'j',
            4 : 'e',
            5 : 'c',
            6 : 't'
}
```

we need to modify documentation. or am I missing something?

**Comment by vweevers** [comment]
Can you please post a complete example? Then it'd be easier to tell what is missing from your setup.

> Both key and value can be of any type as far as levelup is concerned.

I agree we should tweak that sentence. Does the [Introduction](https://github.com/Level/levelup#introduction) explain it though? Specifically:

> They \[the stores\] typically support strings and Buffers for both keys and values. For a richer set of data types you can wrap the store with [`encoding-down`](https://github.com/Level/encoding-down).
