### ISSUE TITLE
Any method to getting the last 20 results?

### ISSUE THREAD

**Issue by aolin480** [Level/levelup#641]
I am new to LevelDB / Levelup and just stumbled across it, and wanted to use it in a project, but I don't see any mention of getting any number of results. I am building a queue of sorts, and want to process rows, and then remove them after there done. Is LevelUp / LevelDown a great solution in regards to querying results either asc or desc as well as a number of results (last 20, etc)

Thanks,
Kind regards

**Comment by fergiemcdowall** [comment]
Level is a pretty good option for dealing with largeish sorted sets, especially if you are generally interested in the first or last few elements in a set. There is no out-of-the-box support for doing aggregations (such as number of hits in resultset), but it is fairly straight forward to do your own.

I'm not sure if I completely understand your usecase, but maybe [`createReadStream`](https://github.com/Level/levelup#createReadStream) in combination with the `limit` option could work for the reads? Listen for the `data` event and do whatever needs to be done for each result (such as removing them).

**Comment by vweevers** [comment]
And if you need something faster for small result sets, you could use [`iterator`](https://github.com/Level/levelup#iterator) with `limit` (and perhaps `highWaterMark`).

**Comment by aolin480** [comment]
Thank you @fergiemcdowall and @vweevers. I will check these solutions out!

**Comment by vweevers** [comment]
Feel free to reopen if you have further questions. And welcome to LevelDB :) Have fun!
