### ISSUE TITLE
Synchronous Callbacks

### ISSUE THREAD

**Issue by ccorcos** [Level/levelup#642]
Why aren't callback called synchronously? Its a shame that `level-mem` can't work work synchronously as an in-memory cache.

https://github.com/Level/mem

**Comment by vweevers** [comment]
> Why aren't callback called synchronously?

For consistency with other stores, and to dezalgo.

> Its a shame that `level-mem` can't work work synchronously as an in-memory cache.

Synchronous variants of methods (e.g. `getSync`) have also been suggested for `leveldown`: https://github.com/Level/leveldown/issues/372. We're open to it.

**Comment by ccorcos** [comment]
Neat-O. I will try to see what I can do.

**Comment by ccorcos** [comment]
Looking through everything, there are so many packages that its going to be a pain to make everything work synchronously. In the meantime, I tried a more "engineered" solution for making `level-mem` synchronous and it works quite well... 😄 

https://github.com/Level/mem/pull/50
