### ISSUE TITLE
OpenError: IO error: lock ./mydb/LOCK: already held by process

### ISSUE THREAD

**Issue by avril-verhaeghen** [Level/levelup#667]
`(node:36822) UnhandledPromiseRejectionWarning: OpenError: IO error: lock ./db-users/LOCK: already held by process
    at /Users/avrilverhaeghen/Development/Finance/OBBF-API/node_modules/levelup/lib/levelup.js:96:23`

Running this issue now, can't seem to find a lot of documentation about this. How can I unlock the LOCK file? Thanks

**Comment by vweevers** [comment]
LevelDB can only be opened by one process at a time. When that process closes the db, the lock is released.

**Comment by ralphtheninja** [comment]
@vweevers Come to think of it, maybe we should put together a FAQ for level?
