### ISSUE TITLE
vulnerabilities fix

### ISSUE THREAD

**Issue by akoushke** [Level/levelup#676]
`bl` dependency needs to be updated please. Let me know If you want me to open a PR for it.

<img width="513" alt="Screen Shot 2019-09-21 at 3 19 51 PM" src="https://user-images.githubusercontent.com/14226615/65378220-739ce780-dc83-11e9-9deb-4f884b931cfc.png">

**Comment by vweevers** [comment]
We removed `bl` in #674, will release soon. Thanks for the report!

**Comment by akoushke** [comment]
@vweevers thanks for the reply. would this be a path/minor update or major?

**Comment by vweevers** [comment]
Next release will be semver-patch.

> it looks like the version had not been updated. do you plan to override the npm lib?

Not sure what you mean.

It doesn't really matter though, `bl` is/was only a devDependency.

**Comment by akoushke** [comment]
Okay got it.
