### ISSUE TITLE
Multiple read streams of key-values

### ISSUE THREAD

**Issue by P0oOOOo0YA** [Level/levelup#683]
Suppose there are `10000` entries in a levelup compatible store and reading all entries using the main thread takes `t`ms. If we use the new [threading](https://nodejs.org/api/worker_threads.html) feature of node to create extra `9` threads in order to read `10` ranges of keys

`1-1000 main_thread`  
`1001-2000 thread2`  
`2001-3000 thread3`  
`...`  
`9001-10000 thread9`  

Does it make the `t` to become `t/10`?

**Comment by vweevers** [comment]
Depends on the store I guess. With `level(down)` it would not matter (as it already uses async workers) or even work (because it doesn't support worker threads).
