### ISSUE TITLE
[question] Recommendation for reseting a batch? 

### ISSUE THREAD

**Issue by CarsonMcKinstry** [Level/levelup#684]
I'm currently working on a data sink that uses LevelUp as its storage layer. It essentially wraps LevelUp in a writable stream that batches incoming data. After the batch hits a certain size, I write that batch and reset it. Isolating this, this is basically what I'm doing:

```
let batch = db.batch();

...

await batch.write();
batch = db.batch();
```

Is that the recommended way to reset a batch? Or is there a better way to do this? I tried `batch.clear()`, but get a `WriteError`, which, for me, is a bit unexpected, as I'd expect it to reset the batch.

**Comment by vweevers** [comment]
After `.write()` is called, no further calls are allowed. I.e. you can't reuse that batch object.

For every new batch of operations, create a new `db.batch()`.

**Comment by vweevers** [comment]
And "clear" means "cancel (the operations added so far)" rather than "reset".
