### ISSUE TITLE
Weird Situation Causes Hang

### ISSUE THREAD

**Issue by yokunjon** [Level/levelup#697]
Hello! I have an electron project that I use leveldown (with levelup wrapper) in it. Currently, there is a weird situation that I am in. I decided on connecting to database in the renderer thread instead of the main to reduce IPC needs. It works OK in that regard, but I use Webpack Dev Server to reload when changes happen and it hangs the renderer 90% of the time when that happens. I tried closing DB with beforeunload event, but couldn't manage to find a reliable solution. I tried debugging it and found it is related to the iterator, but not sure about it.

Currently, I create new renderer and close the old one whenever I receive an update. It is manageable comparing to closing and relaunching the app (which I was doing while I was setting up the DB), but still annoying to a degree. So, what might be the problem, do you have any idea? Thanks.

**Comment by vweevers** [comment]
LevelDB can only be opened by one process at a time. I think when you attempt to close the db in beforeunload, which is synchronous while closing is asynchronous, it doesn't get enough time to complete.

You might like https://github.com/Level/party.

**Comment by yokunjon** [comment]
I also tried preventing the reload and using the close method with the callback (leveldown method) to reload for that reason, but it isn't enough it seems.

Thanks for the suggestion, it would be really helpful, I hope it works. Just a quick question, is there a chance of old connection not closing and keep streaming data to others? It is not a huge issue but I would like to know the possibility.

**Comment by ralphtheninja** [comment]
> I decided on connecting to database in the renderer thread instead of the main to reduce IPC needs

I think this is your problem. Move the db to the main process instead and add some IPC on top. It's also easier for you to swap out the db to something else, or mock it for tests.

**Comment by yokunjon** [comment]
level-party didn't solve it.

@ralphtheninja I thought of this, but there are issues unrelated to level with it. IPC throughput for sync is nowhere to be found, so I avoid that to not block main process. Changes on same key (which is common due to it includes an editor) might result in race conditions with async ones. So, I probably need debouncing and a queue for async ipc. It seems like it isn't possible to solve it otherwise, so I'll go with it.

I didn't expect to get a reply at all due it was unrelated to level, so thanks for quick replies. I am closing the issue as there is no other way in sight except the main process.

**Comment by yokunjon** [comment]
Just wanted to share why it happens in case somebody encounters a similar thing. The issue is unrelated to level, caused by an electron option named allowRendererProcessReuse.
electron/electron#22119
