### ISSUE TITLE
compress(?) or trunk(?) or defragment(?)

### ISSUE THREAD

**Issue by vinnitu** [Level/levelup#706]
Hello!

I use timestamp as a key.
But after analyze date I del ranges of data but seems data directory become even bigger in size...

What can I do implicity to compress/trunk/defragment database after cleanup operations?

**Comment by vweevers** [comment]
Assuming you're using `leveldown`, you're looking for _compaction_: https://github.com/Level/leveldown#leveldown_compactRange
