### ISSUE TITLE
Unable to use the library in reactjs app

### ISSUE THREAD

**Issue by kollachaitanyakrishna** [Level/levelup#711]
Created a new app with the npx create-react-app my-app

Added: https://reactgo.com/react-trigger-button-click/

Modified button click with  steps mentioned in readme.

![image](https://user-images.githubusercontent.com/64516009/102083823-2d104b80-3e3a-11eb-9f7b-f52d4a0aa07f.png)

**Comment by vweevers** [comment]
Please provide a complete example so that we can assist you.
