### ISSUE TITLE
Levelup creates .LDB file every time the database is opened again

### ISSUE THREAD

**Issue by niikku** [Level/levelup#712]
In my application I'm using levelup to write a few values into a database, however I noticed that every time my node script restarts, it creates a new .LDB file in the database directory. Is this intended behavior? I call `levelup(leveldown('./db/myDatabase'));` every time my code starts, and it basically creates a new .LDB file when it starts again. Also calling `db.close()` has no effect for me. Is this intended behavior, a problem with levelDB or a flaw in my coding? I'd love to know.

Best regards,

Nick

**Comment by ralphtheninja** [comment]
It's intended behavior.

**Comment by huhengyuan** [comment]
> It's intended behavior.
How to solve this problem? I don't want to create ldb files frequently.
