### ISSUE TITLE
@types/levelup is missing `getMany`

### ISSUE THREAD

**Issue by sebastianst** [Level/levelup#729]
The [TS types of `levelup`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/levelup) (and possibly other type declarations like for `abstract-leveldown`) are missing the `getMany` functions.

**Comment by Bonaventure00916** [comment]
Hello 
I have encountered the worst version of my life with my account verification and this has been the issue for up to five months plus now , I have submitted all requests documents but it's seems verifying it seems a difficult decision for those in charge , I'm not expecting this such from system like blockchain

**Comment by sebastianst** [comment]
@Bonaventure00916 wrong issue?

**Comment by vweevers** [comment]
More than that, wrong repository :)

https://github.com/Level/levelup/issues/735#issuecomment-1019360861

**Comment by vweevers** [comment]
Closing for the same reason as https://github.com/Level/community/issues/104#issuecomment-1079792406.
