### ISSUE TITLE
Questions about how to retrieve the existing data in the database

### ISSUE THREAD

**Issue by jozhi** [Level/levelup#730]
I am a beginner in leveldb and I found a magical situation.

I used various methods to retrieve the stored data. In the end, I was surprised to find in an issue that the option of createKeyStream could use leq as the retrieval condition. I was shocked at that time. Because I have never experienced this way to learn a new technology, I need to come from other unofficial channels for the parameters that are not indicated in the official document but are actually available.
My question now is, how many of these parameters are hidden in other weird places that we need to rely on God's guidance to find them?

**Comment by vweevers** [comment]
What do you mean by leq? If you mean the `lt` option, that is documented.

**Comment by jozhi** [comment]
> documented

I'm talking about this query parameter
  db.createKeyStream({ leq: "" })

**Comment by vweevers** [comment]
That's not supported by any module under the Level org. I have not seen it in the wider ecosystem either.

**Comment by jozhi** [comment]
> That's not supported by any module under the Level org. I have not seen it in the wider ecosystem either.

Let me prove him

  // package.json
`
{
  "name": "nodewebserver",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "dev":"node app.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.1",
    "leveldown": "^6.1.0",
    "levelup": "^5.1.1"
  }
}
`
// app.js

`
let express = require("express");
let app = express();
 
var levelup = require('levelup')
var leveldown = require('leveldown')

// 1) Create our store
var db = levelup(leveldown('./mydb2'))


const dbStore = {
  put:(key,value,cb)=>{
    db.put(key, value, function (err) {
      if (err) return console.log('Ooops!', err) // some kind of I/O error

      console.log(`{'${key}':'${value}}'}  put success!`)
      cb && cb()
    })
  },
  get:(key)=>{
    // 3) Fetch by key
    db.get(key, function (err, value) {
      if (err) return console.log('Ooops!', err) // likely the key was not found
      // Ta da!
      console.log(`${key}=` + value)
      return value
    })
  }
}

// findKey
function findKey(snippet, callback) {
  const keys= []
  //  Look here      ⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇
  //  Look here      ⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇
  //  Look here      ⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇
  db.createKeyStream({ leq: snippet })
    .on('data', function (data) {
      let strData = data.toString("utf8")
      if(strData.indexOf(snippet)>-1){
        keys.push(strData)
      }
    })
    .on('end', function () {
      console.log('keys:',keys)
    })
}


dbStore.put('codeData-111',`0,32.1,2.34,32.1,32.1,1,32.1,1`)
dbStore.put('codeData-222',`0,32.1,2.34,32.1,32.1,1,32.1,1`)
dbStore.put('codeData-333',`0,32.1,2.34,32.1,32.1,1,32.1,1`)
dbStore.put('codeData-444',`0,32.1,2.34,32.1,32.1,1,32.1,1`)
dbStore.put('codeData-555',`0,32.1,2.34,32.1,32.1,1,32.1,1`)
dbStore.put('codeData-666',`0,32.1,2.34,32.1,32.1,1,32.1,1`)

findKey('codeData-222')


const listener = app.listen(4003)
console.log(`  http://localhost:${listener.address().port}`, );
`
After running you will get
`
keys: [ 'codeData-222' ]
`
So, why did he not appear in the official document?

**Comment by jozhi** [comment]
> > That's not supported by any module under the Level org. I have not seen it in the wider ecosystem either.
> 
> Let me prove him
```
{
  "name": "nodewebserver",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "dev":"node app.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.1",
    "leveldown": "^6.1.0",
    "levelup": "^5.1.1"
  }
}
```

// app.js

```
let express = require("express");
let app = express();
 
var levelup = require('levelup')
var leveldown = require('leveldown')

// 1) Create our store
var db = levelup(leveldown('./mydb2'))


const dbStore = {
  put:(key,value,cb)=>{
    db.put(key, value, function (err) {
      if (err) return console.log('Ooops!', err) // some kind of I/O error

      console.log(`{'${key}':'${value}}'}  put success!`)
      cb && cb()
    })
  },
  get:(key)=>{
    // 3) Fetch by key
    db.get(key, function (err, value) {
      if (err) return console.log('Ooops!', err) // likely the key was not found
      // Ta da!
      console.log(`${key}=` + value)
      return value
    })
  }
}

// findKey
function findKey(snippet, callback) {
  const keys= []
  //  Look here      ⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇
  //  Look here      ⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇
  //  Look here      ⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇
  db.createKeyStream({ leq: snippet })
    .on('data', function (data) {
      let strData = data.toString("utf8")
      if(strData.indexOf(snippet)>-1){
        keys.push(strData)
      }
    })
    .on('end', function () {
      console.log('keys:',keys)
    })
}


dbStore.put('codeData-111',`0,32.1,2.34,32.1,32.1,1,32.1,1`)
dbStore.put('codeData-222',`0,32.1,2.34,32.1,32.1,1,32.1,1`)
dbStore.put('codeData-333',`0,32.1,2.34,32.1,32.1,1,32.1,1`)
dbStore.put('codeData-444',`0,32.1,2.34,32.1,32.1,1,32.1,1`)
dbStore.put('codeData-555',`0,32.1,2.34,32.1,32.1,1,32.1,1`)
dbStore.put('codeData-666',`0,32.1,2.34,32.1,32.1,1,32.1,1`)

findKey('codeData-222')


const listener = app.listen(4003)
console.log(`  http://localhost:${listener.address().port}`, );
```

After running you will get
```
keys: [ 'codeData-222' ] 
```
So, why did he not appear in the official document?
