### ISSUE TITLE
Ref Level/abstract-leveldown#379, Level/community#83, Level/community#79, Level/levelup#726.#3205721

### ISSUE THREAD

**Issue by Bonaventure00916** [Level/levelup#738]
Ref Level/abstract-leveldown#379, Level/community#83, Level/community#79, Level/levelup#726.

Almost the same as https://github.com/Level/level/pull/207.

__Originally posted by @vweevers in https://github.com/Level/levelup/pull/727__#3205721

**Comment by vweevers** [comment]
Blocked because of https://github.com/Level/levelup/issues/735, https://github.com/Level/levelup/issues/729#issuecomment-1028195562, https://github.com/Level/community/issues/101#issuecomment-1028201033 and now this.
