### ISSUE TITLE
incorrect promises implementation

### ISSUE THREAD

**Issue by dcharbonnier** [Level/levelup#741]
`await db.open()` will never reject and an error event will be emitter crashing the process.

a dirty workaround that should not add issue the day this is fixed:
```
await new Promise<void>((resolve, reject) => {
        db.once("error", (err) => reject(err));
        db.open((err) => {
          if (err) {
            reject(err);
          } else {
            resolve();
          }
        });
      });
```

**Comment by vweevers** [comment]
Duplicate of https://github.com/Level/levelup/issues/710

**Comment by dcharbonnier** [comment]
#710 is closed, is this fix not released ?
